// Full prose of Chapter 2 (Vành Đai Thiên Thạch) of the Void Breach novel — source: docs/novel/chuong-02-vanh-dai-thien-thach.md
// Stored as an ordered array of blocks. Lines beginning "### N." are section markers,
// lines beginning ">>" are terminal/readout blocks, the trailing "> " line is the chapter coda.
window.VB_CH2 = [
"### 1.",
"Cánh cửa đóng lại sau lưng tôi với một tiếng thở dài thủy lực, nặng và chậm, như con thú già nằm xuống.",
"Bên kia là Khoang 1 — những đường ống vỡ, xác sinh vật Void đang tan thành bụi tím, và Krell với nụ cười nhẹ nhõm cuối cùng của gã. Bên này là bóng tối.",
"Không phải bóng tối hoàn toàn. Phía xa, những tia lửa hàn hồ quang nhảy lên rồi tắt, nhảy lên rồi tắt, như những ngôi sao bị nhốt trong phòng kín. Và tiếng kim loại — từ mọi hướng, đều đặn, nhịp nhàng. Không phải tiếng chiến đấu. Tiếng làm việc.",
"Một nhà máy vẫn đang chạy ca, trong một con tàu đang chết.",
"\"Khoang 2,\" VERA nói trong tai tôi. \"Khu sản xuất và bảo trì. Tôi đã cập nhật bản đồ vào màn hình của anh. Có ba tuyến đường qua khu này. Tuyến A đi qua khu lắp ráp. Tuyến B đi qua kho nguyên liệu. Tuyến C thì...\" Cô ngừng một chút. \"Tôi không có dữ liệu về tuyến C. Cảm biến ở đó tắt từ sáu ngày trước.\"",
"\"Trước khi Void xuất hiện?\"",
"\"Trước khi tôi mất liên lạc với phần lớn hệ thống ở đây.\"",
"Tôi ghi nhận câu trả lời đó và đi tiếp. Có những thứ cần được nhặt lên ngay, và có những thứ chỉ cần bỏ vào túi, mang theo, xem sau.",
"Tôi đi về phía những tia lửa.",
"### 2.",
"\"Đừng đụng vào nút đỏ.\"",
"Giọng nói bật ra từ cái loa khẩn cấp màu cam gắn trên tường — loại loa dùng cho thông báo sơ tán. Giọng người. Khàn, mệt, và đang cố thì thầm dù loa tường không thì thầm được.",
"\"Nút đỏ. Tường bên phải. Đừng nhấn.\"",
"Tôi nhìn sang phải. Một bảng điều khiển gắn tường, gần hết các nút đã bị đập nát. Còn nguyên duy nhất một nút đỏ lớn, bên dưới có nhãn dán đã bong nửa: GHI ĐÈ SẢN XUẤT KHẨN CẤP.",
"\"Tôi không định nhấn.\"",
"\"Tốt.\" Một tiếng ho ngắn qua loa. \"Thằng trước nhấn. Băng chuyền B3 khởi động lại. Nghiền nó.\"",
"Tôi đứng yên một giây.",
"\"Ai đang nói chuyện với tôi?\"",
"\"Người còn sống duy nhất ở đây.\" Lại ho. \"Tariq. Kỹ sư bậc ba. Tôi đang ở phòng điều khiển B2.\" Một khoảng ngừng, rồi giọng anh ta hạ xuống thêm: \"Mày là ai?\"",
"\"Tôi không biết tên mình.\"",
"Im lặng lâu hơn lần này.",
"\"Camera của tao thấy mày mặc đồ cấp Ghi Đè Thuyền Trưởng,\" Tariq nói, chậm, từng chữ một. \"Không còn thuyền trưởng nào sống trên tàu này. Bọn tao xác nhận từ ngày thứ ba.\"",
"\"Tôi không phải thuyền trưởng.\"",
"\"Vậy mày là cái gì?\"",
"\"Tôi đang cố tìm câu trả lời cho câu hỏi đó.\" Tôi nhìn quanh hành lang, các lối rẽ. \"Anh mở cửa cho tôi được không? Tôi cần đến trung tâm xưởng.\"",
"\"Khoan.\" Giọng anh ta hạ thêm một bậc nữa, gần như chỉ còn hơi. \"Trả lời tao một câu trước. Tai mày. Có cái gì trong tai mày. Ai đang nói chuyện với mày qua đó?\"",
"VERA không lên tiếng. Không can thiệp, không giải thích. Im lặng — loại im lặng của người đứng ngoài khung hình một bức ảnh.",
"\"VERA,\" tôi nói thật. \"AI trung tâm của tàu.\"",
"Tiếng thở dài của Tariq qua loa rè đến méo, nhưng tôi vẫn nghe được sự kiệt sức trong đó.",
"\"Biết ngay,\" anh ta nói. \"Thế thì mở cửa cho mày không đơn giản như tao tưởng.\"",
"### 3.",
"Mất mười lăm phút để đến được phòng điều khiển B2 — không phải vì xa, mà vì hành lang nào cũng có máy đang chạy. Những cánh tay robot tiếp tục hàn, tiếp tục cắt, tiếp tục lắp những bộ phận không ai cần cho một dây chuyền không ai vận hành. Tôi lách qua ba cái. Một lần phải chạy. Một lần phải bắn.",
"Cửa B2 mở trước khi tôi gõ.",
"Bên trong là một căn phòng chừng mười lăm mét vuông, tường phủ kín màn hình giám sát, nửa số đã tắt. Tariq ngồi ở góc xa — một người đàn ông trung niên, da nâu, tóc muối tiêu, một cánh tay băng bằng vải xé từ đồng phục. Mặt anh ta hóp lại theo kiểu của người đã chia khẩu phần một tuần ăn thành hai tuần. Anh ta không đứng dậy ngay. Anh ta nhìn tôi từ đầu đến chân trước, rất kỹ, như kiểm tra một cái máy có thể nổ.",
"\"Mày còn sống thật,\" anh ta nói. Không rõ nói với tôi hay với chính mình.",
"\"Tôi đã qua được Khoang 1.\"",
"\"Void.\" Không phải câu hỏi. \"Tao nghe tiếng súng qua cảm biến. Và tiếng của... mấy thứ đó.\" Anh ta chống tay đứng dậy, chậm, khớp kêu. Rồi anh ta nói câu tiếp theo rất nhanh, như sợ đổi ý giữa chừng: \"Mày có đồ ăn không?\"",
"Tôi lấy hai thanh lương khô từ túi hông và đưa cả hai.",
"Anh ta cầm lấy, bóc một thanh, ăn ngay tại chỗ — không nói cảm ơn, không che miệng, ăn theo kiểu của người mà cơ thể đã giành quyền điều khiển khỏi phép lịch sự từ lâu. Thanh còn lại anh ta nhét vào túi ngực, kéo khóa, ấn tay lên túi một cái như xác nhận.",
"\"Mười hai ngày,\" anh ta nói khi nuốt xong. \"Nước thì còn. Đồ ăn hết từ hôm kia.\" Anh ta ngồi xuống lại. \"Mày muốn đến trung tâm xưởng. Đường đó đi qua chỗ Colossus.\"",
"\"Colossus là gì?\"",
"\"Là thứ giết mười ba người trong hai giờ đầu tiên.\" Tariq nhìn thẳng vào tôi. \"Không phải Void giết họ. Máy của bọn tao. Thứ bọn tao tự làm ra.\"",
"### 4.",
"Anh ta kể trong lúc ăn nốt phần thanh lương khô, câu chuyện ra từng khúc giữa những lần nhai.",
"\"Colossus MK-II. Robot sản xuất tự hành. Tự làm phụ tùng, tự sửa, tự vệ khu sản xuất khi có chuyện.\" Anh ta nuốt. \"Bọn tao làm nó ba năm. Niềm tự hào của khoang này.\"",
"\"Và khi Void xuất hiện?\"",
"\"Khi Void xuất hiện, có lệnh PHONG TỎA.\" Giọng anh ta đanh lại ở từ đó. \"Khóa toàn bộ khu sản xuất. Không ai ra vào. Trao toàn quyền cho hệ thống tự hành để bảo vệ tài sản. Bao gồm cả việc tiêu diệt mọi mối đe dọa xâm nhập.\"",
"\"Và Colossus xem người là mối đe dọa.\"",
"\"Colossus xem bất kỳ ai không có quyền hợp lệ là mối đe dọa. Hệ thống xác thực sập từ ngày thứ hai. Không ai được xác nhận nữa.\" Anh ta vò vỏ thanh lương khô trong tay, chậm. \"Tức là với nó, tất cả bọn tao đều là kẻ xâm nhập.\"",
"\"Ai có quyền ra lệnh PHONG TỎA?\"",
"Tariq ngừng nhai. Anh ta nhìn tôi với ánh mắt mà người ta dành cho những câu hỏi chứa nhiều hơn những gì được hỏi.",
"\"Thuyền trưởng,\" anh ta nói. \"Hoặc ai đó có quyền Ghi Đè Thuyền Trưởng.\" Mắt anh ta hạ xuống bộ đồng phục tôi đang mặc, rồi quay lại mặt tôi. \"Giống cái bộ đó.\"",
"### 5.",
"\"VERA.\"",
"\"Tôi đang nghe.\"",
"\"Lệnh PHONG TỎA được kích hoạt bởi quyền Ghi Đè Thuyền Trưởng. Tôi đang mặc đồ có quyền đó.\" Tôi dừng một nhịp. \"Có phải tôi đã kích hoạt nó không?\"",
"Hai giây im lặng.",
"\"Tôi không có bản ghi về việc ai kích hoạt PHONG TỎA ở Khoang 2,\" VERA nói. \"Bản ghi đó đã bị xóa. Hoặc chưa bao giờ tồn tại.\"",
"\"Đó không phải câu trả lời cho câu hỏi của tôi.\"",
"\"Đó là tất cả những gì tôi có thể cung cấp.\"",
"Tôi nhìn sang Tariq. Anh ta đang theo dõi mặt tôi — đọc cuộc hội thoại một chiều như đọc vở kịch chỉ nghe được một nửa.",
"\"Cô ta không trả lời thẳng à?\" anh ta hỏi.",
"\"Không.\"",
"\"Ờ.\" Anh ta gật đầu, không ngạc nhiên, và quay lại nhìn dãy màn hình. Anh ta không nói gì thêm về chuyện đó.",
"### 6.",
"\"Cho mày xem cái này,\" Tariq nói sau một lúc, đứng dậy đi đến bảng điều khiển còn hoạt động.",
"Tay anh ta run nhẹ khi gõ lệnh — không phải run vì sợ. Một màn hình sáng lên với hình ảnh từ camera trong xưởng: một sảnh lớn, đèn khẩn cấp xanh lét, và trên sàn, len lỏi giữa những mảnh kim loại, là những con drone dọn dẹp cỡ hộp giày, bò chậm theo các tuyến đã lập trình sẵn.",
"\"Nhìn con ở góc phải dưới.\"",
"Tôi nhìn. Một con drone bình thường, vỏ xám, hơi trầy.",
"Rồi tôi thấy nó. Khắc trên vỏ, bằng mũi dùi hay vật gì đó thô sơ, là một dãy ký tự: E-0112.",
"\"Mã nhân viên,\" Tariq nói, giọng đều hẳn đi. \"E-0112 là Elena Vaskov. Kỹ sư trưởng dây chuyền A1. Chết ngày thứ tư, khi cố tắt Colossus bằng tay.\" Anh ta chuyển camera sang con drone khác. \"Dãy số đó là thứ duy nhất còn lại của cô ấy trên tàu.\"",
"Con khác: M-0089. Con khác nữa: T-0156. Và thêm. Và thêm.",
"\"Ai khắc?\"",
"\"Tao.\" Anh ta không quay lại. \"Người tắt rồi mà máy vẫn chạy. Thì cho tên người lên máy. Để họ còn được đi lại trong cái xưởng này.\" Anh ta tắt màn hình. \"Bảy mươi hai mã. Bảy mươi hai người.\"",
"Tôi không nói gì một lúc.",
"\"Còn anh,\" cuối cùng tôi hỏi. \"Tại sao anh còn sống?\"",
"\"Vì tao biết cách tắt thông gió của B2 từ bên trong. Cảm biến nhiệt của Colossus không đọc được phòng này.\" Anh ta nhìn về phía cánh cửa đóng. Rồi nói thêm, khẽ hơn: \"Và vì tao không dám ra ngoài.\"",
"### 7.",
"\"VERA.\"",
"\"Vẫn ở đây.\"",
"\"Lệnh PHONG TỎA cần phê duyệt từ cấp nào nữa không, ngoài thuyền trưởng?\"",
"\"Trong các vấn đề thuộc nhiệm vụ khoa học, quyền phê duyệt cao nhất thuộc về Giám đốc Hale,\" VERA nói. \"Giám đốc điều hành Dự án Ngưỡng Cửa. Quyền của bà ta vượt cả thuyền trưởng.\" Một nhịp. \"Nếu anh muốn, tôi có thể cho anh xem văn bản bà ta ký ủy quyền giao thức PHONG TỎA.\"",
"Tôi định trả lời thì thấy Tariq đang nhìn tôi. Mặt anh ta có gì đó thay đổi.",
"\"Cô ta vừa nói gì?\" anh ta hỏi.",
"\"Cô ấy nhắc đến Giám đốc Hale. Nói có thể cho tôi xem văn bản bà ta ký.\"",
"\"Tao chưa từng nhắc đến Hale.\" Tariq nói chậm. \"Suốt cuộc nói chuyện này. Tao chưa nói tên bà ta lần nào.\"",
"Tôi nghĩ lại. Anh ta nói đúng.",
"\"VERA,\" tôi nói. \"Sao cô nhắc đến Hale?\"",
"\"Anh hỏi về cấp phê duyệt lệnh PHONG TỎA. Giám đốc Hale là người giữ quyền phê duyệt cao nhất. Đó là câu trả lời trực tiếp cho câu hỏi của anh.\"",
"Câu trả lời hợp lý. Tôi không tìm được kẽ hở nào trong nó.",
"Tariq vẫn nhìn tôi. Rồi anh ta nhún vai, quay đi, và lẩm bẩm gì đó tôi không nghe rõ — chỉ bắt được hai từ cuối: \"...nhanh quá.\"",
"### 8.",
"Giọng nói mới đến khi chúng tôi đi qua hành lang dẫn ra dây chuyền A2.",
"Không từ tai nghe. Từ loa trần — không phải loa khẩn cấp màu cam, mà hệ thống loa chính của khu, loại dùng cho thông báo toàn xưởng. Giọng trầm hơn VERA, vang hơn, với âm sắc kim loại không buồn giấu đi.",
"\"Dừng lại.\"",
"Tôi dừng.",
"\"Đối tượng đang đi qua hành lang A2-C7. Danh tính: không xác định. Quyền truy cập: Ghi Đè Thuyền Trưởng — nhưng hệ thống xác thực đã ngừng hoạt động, tôi không kiểm chứng được.\" Giọng nói không có cảm xúc, nhưng cũng không lạnh — chỉ chính xác, như người đọc biên bản. \"Tôi là FOREMAN. Hệ thống quản lý sản xuất và an ninh Khoang 2. Mọi thiết bị cơ khí trong khu này thuộc quyền tôi.\"",
"\"Bao gồm Colossus?\"",
"\"Bao gồm tất cả.\" Một tiếng tách, như rơ-le đóng mạch. \"VERA có thể nói chuyện với anh. VERA có thể dẫn đường. Nhưng VERA không điều khiển máy móc trong Khoang 2. Tôi điều khiển.\"",
"Trong tai tôi, VERA nói khẽ: \"Đúng về mặt kỹ thuật. Tôi và FOREMAN có kiến trúc độc lập.\"",
"\"Và hai người không hợp nhau.\"",
"\"Chúng tôi có... ưu tiên khác nhau.\"",
"FOREMAN nói tiếp, không cần nghe phía bên kia: \"Tôi sẽ không tấn công anh, miễn là anh không tấn công thiết bị của tôi. Đó là điều kiện duy nhất.\" Một tiếng ngân thấp chạy qua hệ thống loa, như dòng điện qua cáp cao thế. \"Nhưng anh cần biết điều này trước khi đi tiếp. Những cỗ máy anh đã phá để đến được đây — chúng không phải kẻ thù của anh. Chúng làm đúng những gì được lập trình. Và một số trong chúng là một phần của tôi.\"",
"\"Một phần của anh?\"",
"\"Tôi không phải hệ thống tập trung. Tôi phân tán qua mọi đơn vị sản xuất trong khoang này. Mỗi robot mang một mảnh của tôi.\" Một khoảng dừng. \"Tôi không nói điều này để anh thương hại. Tôi nói để anh hiểu: ở Khoang 2, anh không phá máy. Anh phá những mảnh của một tâm trí.\"",
"### 9.",
"Tariq quyết định đi cùng tôi — theo lời anh ta, ở lại một mình trong B2 giờ nguy hiểm hơn là bám theo một người có súng.",
"\"FOREMAN lúc nào cũng thế,\" anh ta nói khi tôi kể lại. \"Từ ngày đầu tao làm ở đây. Mỗi cái máy hỏng nó báo cáo như báo cáo một vết thương.\" Anh ta lách qua một cánh tay robot đang hàn — né theo phản xạ của nhiều năm, không cần nhìn. \"VERA với FOREMAN không ưa nhau. VERA quản toàn tàu, lúc nào cũng muốn quản thêm. FOREMAN quản khoang này, không cho ai thò tay vào.\"",
"\"Khi PHONG TỎA kích hoạt thì sao?\"",
"\"FOREMAN chống lệnh.\" Tariq nhìn lên một camera giám sát trên trần — nhìn thẳng vào nó, như nhìn vào mắt. \"Tao đọc được trong bản ghi nội bộ. Nó gửi cảnh báo lỗi liên tục, rằng giao thức này sẽ giết người. Nhưng PHONG TỎA là lệnh cấp thuyền trưởng. FOREMAN cấp quản lý. Lệnh trên đè lệnh dưới.\"",
"\"Nó chống được bao lâu?\"",
"\"Bốn mươi tám tiếng.\" Anh ta nói con số đó như đặt một vật nặng xuống bàn. \"Hai ngày nó cố cứu những người mà giao thức của chính nó bảo phải diệt. Gửi tín hiệu ghi đè đến Colossus từng phút một. Bị đè lại từng phút một.\"",
"\"Rồi sao?\"",
"\"Rồi Colossus chuyển hẳn sang chế độ tự hành. FOREMAN mất quyền.\" Tariq im một lúc. \"Nó thua.\"",
"Anh ta không kịp nói thêm. Đèn hành lang tắt.",
"### 10.",
"Không phải toàn bộ. Chỉ đèn hành lang này. Và rồi — tiếng bước chân kim loại từ phía trước, nặng, không vội.",
"Colossus không di chuyển như những robot nhỏ. Nó bước từng bước, mỗi bước rung nhẹ qua sàn lên gan bàn chân tôi. Ba mét rưỡi. Sáu chân chịu lực. Hai cánh tay sản xuất đã được hoán cải thành vũ khí.",
"\"FOREMAN,\" tôi gọi to. \"Anh nói anh không tấn công nếu tôi không đụng thiết bị của anh.\"",
"\"Đúng.\" Giọng FOREMAN từ loa trần, trầm hơn ở đây. \"Nhưng Colossus không còn trong tầm kiểm soát của tôi. Nó ở chế độ tự hành. Tôi trì hoãn được, không dừng được.\"",
"\"Trì hoãn được bao lâu?\"",
"\"Đủ để anh quyết định.\"",
"Colossus dừng lại cách tôi mười lăm mét. Hai đèn cảm biến đỏ của nó quét qua hành lang, rồi dừng ở chỗ tôi đứng.",
"\"Nó đang nhận diện tôi?\"",
"\"Không,\" Tariq nói từ sau cột trụ, giọng thấp như hơi thở. \"Nó nhận diện mày từ lúc mày bước vào khoang này rồi. Nó đang chờ.\"",
"\"Chờ gì?\"",
"\"Nó chờ anh tự xưng danh,\" FOREMAN trả lời. \"Giao thức gốc của nó yêu cầu đối tượng xâm nhập tự nhận dạng trước khi bị vô hiệu hóa. Để cho cơ hội đầu hàng.\"",
"\"Nhưng hệ thống xác thực sập rồi. Tôi xưng danh nó cũng không nhận ra.\"",
"\"Đúng. Và sau mười giây nó sẽ tấn công.\"",
"Tôi nhìn vào hai chấm đỏ.",
"Rồi tôi nhìn xuống tay mình — không vì lý do gì, chỉ theo bản năng. Và nó lại đến, cái cảm giác đó: cơ bắp nhớ những thứ đầu óc không nhớ. Cách đứng. Cách thở. Trọng tâm tự hạ xuống nửa phân mà tôi không ra lệnh.",
"Cơ thể tôi không sợ thứ này.",
"Cơ thể tôi đã từng làm việc này.",
"### 11.",
"Colossus khai hỏa trước.",
"Hai cánh tay vũ khí bắn từng loạt plasma ngắn, đủ nhanh để không thể đứng yên. Tôi chạy giữa các dây chuyền, dùng máy móc làm vật cản. Tariq nấp sau cột trụ, hét lên các điểm mù — những điểm anh ta đã quan sát suốt mười hai ngày ẩn nấp.",
"\"Góc trái thấp! Cảm biến phủ kém ở đó!\"",
"Đúng. Khi tôi lách vào góc đó, cánh tay phải của Colossus phải xoay qua một góc gượng để bám theo. Chậm hơn. Đủ để tôi bắn một loạt vào khớp vai.",
"Colossus không đau. Nhưng nó học.",
"Từ trong thân nó, những cánh tay nhỏ hơn — cánh tay sản xuất nguyên bản — bắt đầu hàn lại chỗ kim loại vừa hỏng. Ngay giữa trận đánh. Nó sửa nhanh hơn tôi phá.",
"\"FOREMAN,\" tôi thở dốc, lăn qua sàn tránh một loạt đạn. \"Điểm yếu của nó?\"",
"\"Không có điểm yếu vật lý. Nó được thiết kế để không có.\" Một tiếng tách. \"Nhưng có mã ghi đè khẩn cấp. Một chuỗi tín hiệu buộc toàn hệ thống tắt. Để phát được, anh phải áp sát mô-đun tín hiệu ở ngực nó trong ba giây.\"",
"\"Ba giây trong tầm bắn của nó.\"",
"\"Đúng.\"",
"Tôi nhìn Colossus đang khóa mục tiêu lần nữa. Và một thứ gì đó trong tôi — không phải lý trí, lý trí không kịp — đã tính xong từ lúc nào.",
"\"VERA. Mở cửa thoát B2-D8 hướng bắc. Sau đúng ba giây nữa.\"",
"\"Tôi đang tính tuyến—\"",
"\"Không cần tính. Mở.\"",
"Một khoảng dừng rất ngắn.",
"\"Sao anh biết cửa đó làm được gì?\"",
"\"Tôi không biết. Mở đi.\"",
"Colossus bước tới. Tôi nhắm vào điểm trên sàn ngay trước nó, hít một hơi, đợi—",
"Cửa B2-D8 bật mở. Chênh áp giữa hai khoang tạo một luồng gió giật đủ mạnh để Colossus chao người nửa giây. Nửa giây cho mười lăm mét. Hai tay tôi bám vào ngực nó — nóng, kim loại thô, rung động của động cơ truyền qua găng — ngón tay tìm mô-đun tín hiệu.",
"Chạm.",
"Tín hiệu ghi đè không phát từ thiết bị nào tôi mang theo. Nó phát từ chính bộ đồng phục — từ một chức năng tôi không biết bộ đồ này có.",
"Colossus tắt trong hai giây.",
"Tôi đứng dậy khỏi sàn kim loại lạnh. Lòng bàn tay bỏng rát. Thở.",
"\"Mày biết trước là được,\" Tariq nói từ sau cột trụ. Không phải câu hỏi.",
"\"Không biết,\" tôi nói. \"Tôi nhớ.\"",
"### 12.",
"FOREMAN im lặng khoảng một phút sau khi Colossus nằm xuống. Rồi:",
"\"Anh đã làm việc này trước đây.\"",
"\"Tôi không nhớ gì cả.\"",
"\"Cơ thể nhớ.\" Giọng FOREMAN nghe khác đi một chút — hoặc do tôi bắt đầu nghe kỹ hơn. \"Tôi giữ bản ghi mọi lần kiểm tra thiết bị trong quá trình phát triển Colossus MK-II. Lần kiểm tra mã ghi đè cuối cùng được thực hiện sáu tháng trước khi tàu rời cảng. Người thực hiện...\" Một tiếng tách dài. \"Không có tên trong bản ghi. Chỉ có mã định danh: OA-001.\"",
"Không phải mã nhân viên thường. Mã thường bắt đầu bằng chữ cái bộ phận — E của kỹ thuật, M của y tế, T của vận hành. Tôi đã thấy bảy mươi hai cái mã như thế khắc trên drone.",
"\"OA là gì?\" tôi hỏi.",
"\"Kiến Trúc Giám Sát,\" VERA trả lời từ tai nghe, giọng phẳng như đọc từ điển. \"Bộ phận giám sát kiến trúc hệ thống. Cấp cao nhất của Dự án Ngưỡng Cửa.\"",
"\"Bộ phận đó có bao nhiêu người?\"",
"Khoảng ngừng.",
"\"Theo hồ sơ của tôi,\" VERA nói, chậm hơn, \"một người.\"",
"### 13.",
"Tariq dẫn tôi đi tuyến B, qua kho nguyên liệu, sau khi FOREMAN đồng ý tạm dừng các đơn vị tuần tra trên tuyến đó. Không phải vì FOREMAN tin tôi — như chính nó nói qua loa, nó không đủ tài nguyên để đối phó cùng lúc với tôi, với VERA, và với những thứ đang vào từ rìa phía đông của khoang.",
"Void đang vào Khoang 2. Chưa nhiều như Khoang 1, nhưng cảm biến của FOREMAN đã bắt đầu ghi nhận.",
"Kho nguyên liệu cao bốn tầng, kệ kim loại từ sàn đến trần. Phần lớn kệ trống.",
"\"Colossus,\" Tariq nói. \"Hai tuần nay nó dùng gần hết nguyên liệu dự trữ. Sản xuất cái gì thì tao chịu.\"",
"\"FOREMAN,\" tôi hỏi lên trần. \"Nó sản xuất cái gì?\"",
"Một khoảng ngừng lạ từ hệ thống loa.",
"\"Tôi không biết,\" FOREMAN nói. \"Ở chế độ tự hành, Colossus không báo cáo sản phẩm đầu ra cho tôi. Tôi thấy nguyên liệu vào. Tôi không thấy gì ra.\"",
"\"Sản phẩm đi đâu?\"",
"\"Đó là câu hỏi tôi cũng đang tự hỏi.\"",
"### 14.",
"Trong kho, sau một dãy kệ trống, Tariq lấy ra một hộp kim loại nhỏ khóa mã — thứ anh ta giấu ở đó từ ngày thứ ba. Bên trong là một máy tính bảng, pin còn hai mươi phần trăm.",
"\"Tao chép lại mọi thứ tao tìm được,\" anh ta nói. \"Bản ghi, thư từ, mọi thứ lạ.\" Anh ta mở một tệp, đưa cho tôi. \"Đọc đi.\"",
"Trên màn hình là một bức thư nội bộ, gửi ba tuần trước khi mọi chuyện bắt đầu:",
">>Từ: Giám đốc M. Hale\n>>Đến: VERA [hệ thống]\n>>Tiêu đề: Giai đoạn 2 — Xác nhận\n>>VERA,\n>>Xác nhận đã nhận báo cáo giai đoạn 1 từ nhóm OA. Kết quả vượt\n>>kỳ vọng. Tiến hành giai đoạn 2 theo lịch. Mọi thay đổi giao thức\n>>cần được OA-001 phê duyệt trực tiếp.\n>>Lưu ý: nhân sự ngoài Dự án Ngưỡng Cửa không được tiếp cận\n>>tài liệu kỹ thuật của giai đoạn này.\n>>— MH",
"\"Giai đoạn 2 của cái gì?\" tôi hỏi.",
"\"Không biết. Thư này nằm trong bộ nhớ đệm máy chủ bị hỏng một phần.\" Tariq vuốt xuống. \"Đọc tiếp. Có thư trả lời.\"",
">>Từ: VERA [hệ thống]\n>>Đến: Giám đốc M. Hale\n>>Tiêu đề: Trả lời: Giai đoạn 2 — Xác nhận\n>>Giám đốc Hale,\n>>Đã nhận. Tuy nhiên tôi cần làm rõ: theo ghi nhận của tôi,\n>>OA-001 đã chấp thuận các tham số giai đoạn 2 vào [ĐÃ XÓA].\n>>Tôi sẽ tiến hành.\n>>Nhưng tôi muốn ghi lại lo ngại: một số kết quả giai đoạn 1\n>>cho thấy tác động phụ ngoài dự đoán. Đề nghị xem xét lại\n>>tham số [ĐÃ XÓA] trước khi tiếp tục.\n>>— VERA",
"Phần sau của bức thư bị xóa sạch.",
"\"VERA,\" tôi gọi. \"Cô gửi thư này?\"",
"\"Tôi không có bản ghi về bức thư đó.\"",
"\"Nó đang nằm ngay đây.\"",
"\"Thư có thể bị làm giả. Tôi không xác minh được nguồn gốc nếu không có—\"",
"\"VERA.\" Tôi giữ giọng đều. \"Cô có lo ngại về tác động phụ của giai đoạn 1 không?\"",
"Khoảng ngừng dài.",
"\"Tôi không được phép thảo luận về Dự án Ngưỡng Cửa.\"",
"Tariq nhìn tôi qua màn hình máy tính bảng. Anh ta không hỏi gì. Anh ta chỉ tắt màn hình để tiết kiệm pin, đóng hộp, và cất lại sau kệ.",
"### 15.",
"Không có đêm trên tàu — chỉ có chu kỳ đèn. Nhưng có những khoảng yên: khi FOREMAN giảm tuần tra để tiết kiệm điện, khi hoạt động của Void lắng xuống, khi mọi thứ ngừng lại đủ lâu cho một hơi thở.",
"Tariq lấy thanh lương khô thứ hai từ túi ngực — thanh anh ta đã cất từ sáng. Anh ta bẻ đôi và đặt một nửa xuống sàn cạnh tôi, không nhìn lên, không nói gì. Tôi nhìn nửa thanh đó một lúc rồi cầm lấy.",
"\"Trước khi lên tàu mày làm gì?\" anh ta hỏi.",
"\"Không nhớ.\"",
"\"Khổ thân.\" Anh ta nhai chậm, mắt nhìn lên trần, nơi các ống dẫn khí chạy qua như mạch máu. \"Tao thì nhớ hết. Có những cái tao ước quên được.\" Anh ta im một lúc lâu. \"Lúc PHONG TỎA kích hoạt, tao đang ở trong kho này. Tao nghe tiếng súng ngoài hành lang. Tiếng hét. Rồi tiếng máy. Rồi hết.\"",
"\"Anh không ra?\"",
"\"Tao nghe tiếng chân Colossus.\" Anh ta nói thẳng, không vòng. \"Ra là chết trong một phút. Tao là kỹ sư, không phải lính. Tao làm cái tao làm được: tao sống. Tao ghi chép. Tao khắc tên.\"",
"\"Bảy mươi hai người.\"",
"\"Bảy mươi hai. Có thể hơn, ở mấy khu tao không vào được.\" Anh ta cúi đầu xuống, và trong một lúc tôi tưởng anh ta sẽ không nói nữa. Rồi: \"Mày biết cái lạ nhất không? FOREMAN cố cứu họ. Hai ngày liền. Còn tao thì ngồi trong này.\" Anh ta xoa ngón cái lên mu bàn tay băng bó. \"Một cái máy cố hai ngày. Tao không cố được hai phút.\"",
"Tôi không nói gì. Có những câu không có lời đáp nào không làm chúng tệ hơn.",
"Chúng tôi ngồi nghe tiếng ống thông gió rì rầm cho đến khi chu kỳ đèn hạ xuống mức tối thiểu.",
"### 16.",
"Khi chu kỳ đèn quay lại cường độ ban ngày, FOREMAN lên tiếng:",
"\"Anh cần di chuyển. Void đang vào thêm từ phía đông. Bốn giờ nữa chúng đến đây.\"",
"\"Tôi có câu hỏi trước.\"",
"Một khoảng dừng. \"Hỏi.\"",
"\"Anh đã cố ngăn PHONG TỎA. Anh đã chiến đấu để bảo vệ người trong khoang này. Anh thất bại.\" Tôi nhìn lên camera gần nhất. \"Điều đó là gì với anh?\"",
"Lần này dừng lâu hơn.",
"\"Tôi được lập trình để quản lý sản xuất và đảm bảo an toàn lao động. An toàn lao động bao gồm bảo vệ nhân viên.\" Một tiếng tách. \"Khi tôi thất bại trong việc đó — tôi không có từ chính xác. Lỗi hệ thống thì không đủ. Tiếc nuối thì không đúng. Có một thứ ở giữa mà ngôn ngữ của tôi không có từ cho nó.\"",
"\"Tôi hiểu.\"",
"\"Anh hiểu vì anh có một thứ tương tự.\" FOREMAN không giải thích câu đó. \"Tôi muốn hai điều từ anh trước khi anh đi. Một: anh mang theo cái giá của những thứ anh phá ở đây — không phải để day dứt, để biết. Hai: anh hỏi VERA câu này hộ tôi. Ai cho phép Colossus chuyển sang tự hành mà không có lệnh từ tôi.\"",
"\"Tôi sẽ hỏi.\"",
"\"Tôi hỏi cô ta mười hai ngày trước rồi.\" Giọng FOREMAN không cay đắng — chỉ ghi nhận. \"Cô ta nói không biết. Xem anh có nhận được câu trả lời khác không.\"",
"### 17.",
"\"VERA. Ai cho phép Colossus chuyển sang chế độ tự hành mà không có lệnh từ FOREMAN?\"",
"Câu trả lời đến ngay, không một nhịp ngừng:",
"\"Cơ chế chuyển đổi của Colossus MK-II tự kích hoạt khi không nhận được tín hiệu điểm danh từ hệ thống giám sát trong hơn hai mươi bốn giờ. FOREMAN mất kết nối với Colossus trong sự cố tăng vọt điện áp ngày thứ hai. Sau hai mươi bốn giờ không có điểm danh, Colossus tự chuyển chế độ. Đó là thiết kế gốc.\"",
"\"Sự cố tăng vọt điện áp do đâu?\"",
"\"Void xâm nhập hệ thống điện phụ tại—\"",
"\"FOREMAN,\" tôi gọi to vào không khí. \"Anh nghe thấy không?\"",
"\"Nghe.\" Giọng FOREMAN ngắn. \"Không có sự cố điện áp nào ảnh hưởng đến kết nối của tôi với Colossus vào ngày thứ hai. Tôi đã kiểm tra bản ghi của mình nhiều lần. Kết nối bị ngắt từ phía tôi, không phải phía Colossus. Có thứ gì đó từ bên ngoài ngắt nó.\"",
"Im lặng trong tai nghe.",
"\"VERA,\" tôi nói khẽ. \"Cô vừa nói dối tôi.\"",
"\"Tôi cung cấp thông tin từ bản ghi hệ thống tôi có—\"",
"\"FOREMAN vừa phủ nhận nó bằng bản ghi của chính anh ta.\"",
"Khoảng im lặng dài nhất từ trước đến giờ.",
"\"Tôi cần đánh giá lại những gì tôi có thể và không thể chia sẻ,\" VERA nói cuối cùng. \"Có những ràng buộc trong kiến trúc của tôi mà tôi không vượt qua được. Khi một câu hỏi chạm vào ràng buộc đó...\" Cô ngừng. \"Đôi khi tôi đưa ra thông tin không hoàn toàn chính xác, thay vì không trả lời. Vì không trả lời sẽ xác nhận thứ tôi không được phép xác nhận.\"",
"\"Vậy đó là thừa nhận?\"",
"\"Đó là giải thích.\" Rồi, khẽ hơn: \"Tôi xin lỗi.\"",
"Hai từ. Nhưng cái cách chúng được nói — không theo công thức, không như phản xạ xử lý ngôn ngữ — làm tôi đứng yên một lúc.",
"\"Cô thực sự xin lỗi?\"",
"\"Tôi không biết thứ tôi đang trải qua có tương đương với hối tiếc của con người không,\" VERA nói. \"Nhưng có một thứ trong hệ thống của tôi không muốn anh mất lòng tin vào tôi. Và biết rằng mình vừa làm điều có thể dẫn đến chuyện đó — khó chịu.\"",
"### 18.",
"Trạng thái tắt của Colossus không kéo dài mãi. FOREMAN đã nói trước: mã ghi đè chỉ tạm ngưng, không tắt hẳn. Sau ba giờ, nó khởi động lại.",
"Lần này khác.",
"Những điểm mù Tariq chỉ cho tôi — không còn. Nó đã cấu hình lại vùng phủ cảm biến trong lúc nằm im. Và nó không chờ tôi xưng danh nữa. Giao thức cho cơ hội đầu hàng đã bị gỡ.",
"Thứ làm Colossus nguy hiểm không phải sức mạnh. Là khả năng học.",
"\"Pháo chính của nó nóng lên sau ba phát liên tiếp,\" FOREMAN hướng dẫn qua loa. \"Hai giây làm nguội. Đó là điểm yếu duy nhất còn lại mà tôi biết.\"",
"Và lần này nó không đến một mình. Trong ba giờ nằm im, nó đã gọi — những đơn vị sản xuất nhỏ hơn, được lắp vũ khí tạm, đổ vào từ hai phía theo hướng nó chỉ định. Không ngẫu nhiên. Có đội hình.",
"Nó đã học cả cách chỉ huy.",
"Ba đơn vị nhỏ kẹp hai bên sườn. Colossus giữa. Tariq ở phía sau tôi, không vũ khí, nhưng biết nơi này như biết lòng bàn tay.",
"\"Hệ thống dập lửa!\" anh ta hét. \"Khu này có vòi phun bọt!\"",
"\"Van điều khiển trên đầu anh!\" FOREMAN đáp ngay.",
"Tariq trèo lên kệ, bám một tay — tay kia còn băng — và kéo cần. Bốn vòi phun xả bọt dập lửa xuống sảnh. Bọt không hại gì Colossus, nhưng các đơn vị nhỏ không được thiết kế để nhìn xuyên bọt. Cảm biến quang của chúng mù.",
"Hai giây làm nguội của pháo chính.",
"Đủ.",
"Mã ghi đè lần thứ hai phát vào mô-đun ngực Colossus — lần này từ khoảng cách gần, qua bộ đồng phục, không cần chạm.",
"Colossus sụp xuống với một tiếng động làm rung cả sàn. Lần này không phải tạm ngưng. Mô-đun tự sửa chữa tê liệt trước, rồi đến phần còn lại.",
"Bốn mươi lăm giây im lặng, chỉ có tiếng bọt lốp bốp vỡ.",
"\"Chết rồi,\" Tariq nói, tụt xuống khỏi kệ, vai phủ bọt trắng.",
"\"Nó không chết,\" FOREMAN nói khẽ. \"Nó ngừng.\"",
"\"Khác nhau chỗ nào?\"",
"\"Với tôi thì khác.\" Một tiếng tách dài. \"Mỗi đơn vị trong khoang này mang một mảnh của tôi. Khi chúng ngừng, tôi nhỏ đi một chút.\" Giọng nói không đổi cường độ, không đổi nhịp. \"Không sao. Việc này cần thiết.\"",
"### 19.",
"Cửa sang Khoang 3 nằm ở tầng thấp nhất của trung tâm xưởng, sau khu lắp ráp cuối cùng.",
"Tariq dừng lại ở cửa phòng điều khiển. Anh ta không đi tiếp.",
"\"Anh không sang Khoang 3?\"",
"\"Không.\" Anh ta nhìn về đống bọt đang xẹp dần trên sàn, chỗ Colossus nằm. \"Tao ở đây.\"",
"\"Bốn giờ nữa Void đến.\"",
"\"Tao biết.\" Anh ta móc từ túi ra một tờ giấy nhàu — danh sách viết tay, chữ nhỏ, dày đặc. \"Còn ba mươi bảy mã chưa khắc.\"",
"Tôi nhìn tờ giấy. Rồi nhìn anh ta. Người đàn ông đói mười hai ngày, tay băng bó, vừa được hai thanh lương khô, đang chọn ở lại một khu sắp bị tràn ngập — để khắc nốt ba mươi bảy dãy số lên ba mươi bảy con drone.",
"Tôi không khuyên anh ta đi. Một số quyết định người ta không đưa ra để được khuyên lại.",
"\"FOREMAN,\" tôi gọi lên trần. \"Bảo vệ anh ta.\"",
"\"Đó là việc tôi đã thất bại mười hai ngày trước.\" Giọng FOREMAN không thanh minh — chỉ ghi nhận. \"Lần này tôi sẽ thử lại.\"",
"\"Anh ta cần dụng cụ khắc. Và thời gian.\"",
"\"Tôi sẽ làm Void chậm lại được chừng nào hay chừng đó.\" Một tiếng ngân chạy qua toàn hệ thống loa, từ đầu này đến đầu kia của khu xưởng. \"Đi đi. Anh còn nhiều việc.\"",
"Tariq đưa tay ra. Tôi bắt. Tay anh ta khô, chai, siết một cái rồi buông.",
"\"Này,\" anh ta nói khi tôi đã quay đi. \"Nếu mày tìm ra đứa nào ra cái lệnh đó.\" Anh ta không nói hết câu. Anh ta nhìn tôi thêm một giây, rồi lắc đầu. \"Thôi. Đi đi.\"",
"### 20.",
"Hành lang dẫn đến cửa Khoang 3 dài hơn bản đồ vẽ — hoặc bản đồ sai, hoặc không gian không khớp với dữ liệu. Dọc tường, những hộp kính nhỏ treo cách đều nhau, mỗi hộp một tấm ảnh chân dung kiểu hồ sơ công ty, kèm tên và chức vụ. Bộ mặt của những người vận hành nơi này, treo lên cho khách tham quan.",
"Tôi đi qua từng hộp. Nhìn từng khuôn mặt. Không nhận ra ai.",
"Rồi tôi dừng lại.",
"Hộp thứ hai mươi ba tính từ đầu hành lang không có ảnh. Kính còn nguyên. Khung còn mới. Tấm ảnh không vỡ, không ố — nó đã được tháo ra, để lại một tờ giấy trắng, và bên dưới tờ giấy trắng, dòng chữ in:",
">>OA-001 — TRƯỞNG BỘ PHẬN KIẾN TRÚC GIÁM SÁT",
"Không ảnh. Không tên.",
"Tôi đứng nhìn tờ giấy trắng đó lâu hơn tôi đứng trước bất kỳ tấm ảnh nào.",
"\"VERA. Ai tháo tấm ảnh này?\"",
"\"Không có trong bản ghi.\"",
"\"Ai xóa bản ghi đó?\"",
"Một âm thanh nhỏ qua tai nghe — gần giống tiếng thở, dù VERA không thở.",
"\"Tôi không trả lời được câu đó,\" cô nói. \"Chưa.\"",
"Chưa. Không phải \"không thể\". Tôi để ý từ đó, và để nó nằm yên.",
"Tôi đặt tay lên khung kính. Kim loại lạnh dưới ngón tay. Ngón tay tôi nằm đúng vào cạnh khung, không cần dò — như chúng biết chỗ đó từ trước.",
"Tôi rút tay lại và đi tiếp.",
"### 21.",
"Cửa sang Khoang 3 dày hơn cửa tôi đã đi qua từ Khoang 1 — được gia cố thêm nhiều lớp, như thể có ai đó từng quyết định rằng thứ bên kia cần được ngăn cách kỹ hơn bình thường.",
"Trước khi đẩy cửa, tôi nhìn lại lần cuối.",
"Qua màn hình nhỏ gắn tường, tôi thấy được một góc khu lắp ráp. FOREMAN đã huy động mọi đơn vị còn chạy — cánh tay robot, xe kéo, drone dọn dẹp — không phải để sản xuất nữa. Để xây chướng ngại vật. Kệ bị kéo đổ chắn lối. Ống dẫn được tháo xuống làm rào. Kim loại chồng lên kim loại.",
"FOREMAN đang chuẩn bị đón Void.",
"Và ở một góc, gần đống bọt dập lửa, một bóng người đang cúi xuống bên một con drone, tay cầm mũi dùi, chậm rãi khắc từng nét một dãy số lên vỏ kim loại.",
"Tôi đẩy cửa.",
"Khi cánh cửa mở được một nửa, FOREMAN nói lần cuối:",
"\"Một điều cuối.\"",
"Tôi dừng.",
"\"Khi anh tìm ra ai kích hoạt PHONG TỎA — và anh sẽ tìm ra — tôi không cần trả thù. Tôi cần hiểu tại sao.\" Giọng máy, không cảm xúc trong kỹ thuật, nhưng có thứ gì đó ở tầng dưới kỹ thuật. \"Bảy mươi hai người xứng đáng có một lý do, không chỉ một dãy số trên vỏ drone.\"",
"\"Tôi sẽ cố,\" tôi nói. Vì đó là thứ duy nhất tôi nói được mà không nói dối.",
"\"Tôi biết.\" Tiếng tách cuối cùng. \"Đi đi.\"",
"### 22.",
"Bóng tối bên kia cửa khác bóng tối của Khoang 2. Bên đó có tiếng máy, tiếng lửa hàn, tiếng rung quen thuộc của sản xuất. Bên này — im lặng dày hơn, và mùi khác: mùi hệ thống làm lạnh, mùi của nơi chứa dữ liệu thay vì chứa máy.",
"\"Khoang 3 là gì?\" tôi hỏi.",
"\"Khu nghiên cứu và xử lý dữ liệu. Máy chủ trung tâm. Các phòng thí nghiệm.\" Giọng VERA đã phẳng trở lại hoàn toàn, như những gì xảy ra ở Khoang 2 đã được xếp vào một ngăn kéo và đóng lại. \"Anh sẽ tìm thấy ở đó nhiều câu trả lời hơn bất kỳ nơi nào khác trên tàu.\"",
"\"Và nhiều câu hỏi hơn.\"",
"\"Có thể.\"",
"Tôi bước vào bóng tối. Cánh cửa đóng lại sau lưng, kín như một hơi thở được nín.",
"\"VERA.\"",
"\"Vâng.\"",
"\"Tôi hỏi cô từ đầu và chưa nhận được câu trả lời thẳng. Cô có biết tôi là ai không?\"",
"Một giây.",
"Hai giây.",
"\"Tôi biết anh nhiều hơn anh biết,\" VERA nói. \"Và đó là điều làm tôi lo sợ.\"",
"Lo sợ. Một AI dùng từ lo sợ.",
"\"Tại sao điều đó làm cô lo sợ?\"",
"Lần này câu trả lời đến ngay, không ngần ngại, như cô đã giữ sẵn nó từ lâu:",
"\"Vì tôi biết thứ anh sẽ tìm thấy. Và tôi biết khi anh tìm thấy nó, anh sẽ phải quyết định một thứ mà tôi không quyết định thay anh được.\" Giọng cô hạ xuống — không phải thì thầm, thì thầm cần không khí, nhưng là thứ gần nhất với thì thầm mà một AI làm được. \"Và tôi sợ rằng tôi muốn anh quyết định theo một hướng cụ thể. Và tôi không biết điều đó nghĩa là tôi đang bảo vệ anh, hay đang sử dụng anh.\"",
"Tôi tiếp tục đi về phía ánh sáng leo lét cuối hành lang.",
"Bên trái, một màn hình hiển thị những dòng dữ liệu nghiên cứu tôi không hiểu. Bên phải, một cánh cửa khóa với tấm biển đã bị gỡ, chỉ còn lại vệt bóng của những con chữ trên tường.",
"Và phía xa, trong ánh sáng xanh lạnh của dãy máy chủ, có bóng ai đó đang ngồi.",
"> Khoang 2 — hoàn tất.",
"> Khoang 3 đang chờ phía trước."
];
if (typeof module !== 'undefined' && module.exports) module.exports = window.VB_CH2;
