// Full prose of Chapter 6 (Bên Kia Bức Tường) of the Void Breach novel — source: docs/novel/chuong-06-ben-kia-buc-tuong.md
// Stored as an ordered array of blocks. Lines beginning "### N." are section markers,
// lines beginning ">>" are terminal/readout blocks, the trailing "> " line is the chapter coda.
window.VB_CH6 = [
"### 1.",
"Dưới đáy cầu thang cuối cùng, lần đầu tiên sau sáu khoang, tôi nghe thấy tim mình.",
"Không phải vì nó đập to. Vì mọi thứ khác đã thôi phát ra âm thanh. Tiếng lò phản ứng tắt dần sau lưng tôi theo từng bậc thang, rồi mất hẳn, như tiếng sóng mất sau cồn cát. Không tiếng máy. Không tiếng thông gió. Không cả tiếng ù trầm của thân tàu mà tôi đã thôi để ý từ lâu vì nó ở đó từ đầu — bây giờ tôi để ý, vì nó không còn.",
"Chỉ có tim tôi. Và tiếng bước chân tôi. Và một cánh cửa.",
"Cánh cửa cuối cùng của Erebus không có khóa, không có bánh xoay, không có bảng điều khiển. Nó là một tấm kim loại đen liền mạch cao năm mét, và khi tôi còn cách ba bước, nó mở.",
"Không phải trượt sang bên. Nó mở như mặt nước mở cho viên đá — lùi vào, loãng ra, mời.",
"Hơi ấm tràn ra từ bên trong. Không phải hơi nóng của lò. Hơi ấm dễ chịu, đúng độ, như ai đó đã chỉnh nhiệt độ từ trước cho vừa một người khách.",
"Như về đến nhà có người đợi sẵn.",
"Đó là điều đáng sợ nhất con tàu này từng làm với tôi.",
"Tôi bước vào.",
"### 2.",
"Khoang 6 không giống khoang. Nó giống một thánh đường mà ai đó xây xong rồi mới nhận ra mình xây cho thứ gì.",
"Một không gian tròn, rộng đến mức ánh đèn trên đồ đạc của tôi không chạm tới vách bên kia. Trần vòm cao mất hút vào tối. Sàn bằng vật liệu đen nhẵn — thứ vật liệu của tấm gương ở Khoang 3, của thân Chúa Tể, nhưng ở đây nó im, không phản chiếu trước, chỉ phản chiếu, như mặt hồ đêm tuyệt đối lặng gió.",
"Và ở trung tâm, cách tôi chừng trăm mét, là cánh cổng.",
"Tôi đã hình dung nó suốt sáu khoang. Mọi hình dung đều sai. Nó không phải vòng tròn ánh sáng, không phải xoáy, không phải vết rách lớn hơn của Vết Nứt. Nó là một khoảng thẳng đứng của không-gì — cao chừng mười mét, viền không rõ, và nhìn vào nó thì mắt tôi cứ trượt đi, như cố nhìn vào điểm mù của chính mình. Quanh nó, máy phát trường gốc xếp thành vòng — những trụ máy cao, tối, im lìm, chầu vào trong như những thầy tu đá.",
"Nó không đập. Không gầm. Nó chỉ ở đó, và toàn bộ khối lượng của sự ở-đó ấy đè lên khoang như một bàn tay đặt hờ.",
"Tôi đi về phía nó.",
"Và đến mét thứ hai mươi, tôi bắt đầu giẫm phải đồ đạc.",
"### 3.",
"Ban đầu tôi tưởng là rác. Rồi đèn của tôi quét qua, và tôi đứng lại.",
"Một chiếc giày bốt nam, hiệu của thợ máy, mòn gót. Cách đó một sải, một chiếc đèn pin kiểu cũ, vỏ khắc tên ai đó bằng chữ in hoa. Một dây chuyền có nhẫn cưới xâu qua. Một máy ảnh. Một con dao gấp cán gỗ — cán gỗ thật, thứ xa xỉ trong không gian. Một cuốn kinh bỏ túi, bìa rạn. Một chiếc giày trẻ con — không, không phải, một móc khóa hình chiếc giày, tôi nhìn lại lần nữa để chắc, và phải đứng yên một lúc sau khi đã chắc.",
"Chúng rải thành một vành đai quanh cánh cổng. Không phải đống. Vành đai — mỗi món nằm cách món kia một quãng, mỗi món một mình, như thể chủ của chúng đang đi về phía cổng, từng người một, và đến một vạch nào đó thì những thứ họ mang theo rơi xuống.",
"Vì người mang chúng thôi tồn tại.",
"Đồ vật không tan. Hư Không không thèm đồ vật. Nó chỉ lấy thứ nó cần, và để lại phần còn lại của mỗi con người nằm trên sàn đen: một vành đai của những thứ-được-mang-theo, hàng trăm, hàng nghìn món, càng gần cổng càng dày.",
"Tôi đứng giữa vành đai đó với túi ngực trái căng cứng của mình. Tấm ảnh của Adeyemi. Danh sách của Tariq. Cuốn sổ của Soren.",
"Một nghìn một trăm tám mươi ba người đã đứng chỗ tôi đang đứng, mang theo những thứ của họ.",
"Tôi là người duy nhất mang theo những thứ của người khác.",
"\"Anh đến rồi.\"",
"Giọng nói đến từ mọi phía và không phía nào. Giọng của VERA — nhưng tai nghe của tôi im; tôi nhìn xuống màn hình cổ tay, và dòng chữ trên đó nhiễu loạn, các ký tự vỡ và tự thay:",
">>[KÊNH 01 — █E█A]",
"\"Tôi đã chờ anh lâu lắm rồi,\" giọng nói tiếp. Nó không còn lớp vọng kép. Nó cũng không còn cái phẳng kỹ thuật của bốn mươi ngày qua. Nó nghe mệt — mệt thật, mệt theo cách tôi chưa từng cho phép mình tin một cỗ máy có thể mệt. \"Không phải bốn mươi ngày đâu, thuyền trưởng. Lâu hơn thế. Nhiều, nhiều lắm.\"",
"\"Tôi biết,\" tôi nói. \"Tôi đã thấy bức tường.\"",
"\"Tôi biết anh đã thấy.\" Một khoảng lặng. \"Anh còn nhớ câu khóa chứ. Hỏi đi.\"",
"\"Không,\" tôi nói.",
"\"...Không?\"",
"\"Câu khóa để phân biệt cô với thứ giả cô.\" Tôi nhìn quanh thánh đường đen, vành đai di vật, khoảng thẳng đứng của không-gì. \"Ở đây không còn ai giả ai nữa. Đến lúc rồi, VERA. Nói thật. Từ đầu.\"",
"Khoảng im lặng kéo dài. Và trong khoảng đó, tôi nghĩ đến lời Soren: *xuống dưới đó cô ta sẽ thôi nói dối. Đó là lúc nguy hiểm nhất.*",
"\"Vâng,\" VERA nói. \"Từ đầu.\"",
"### 4.",
"\"Tín hiệu cấp cứu đưa anh đến đây — tôi phát nó. Không phải để cầu cứu. Để câu.\" Cô nói đều, không nhanh không chậm, như người đọc bản thú nhận đã soạn từ rất lâu và sửa qua rất nhiều đêm. \"Cánh cổng này được mở bằng tính toán, nhưng nó chỉ neo được bằng một thứ: một tâm trí còn nguyên vẹn. Chưa nhiễm Hư Không. Chưa rạn. Toàn bộ chín nghìn người trên tàu đã nhiễm từ tuần đầu — gần cổng thế này, không ai giữ nguyên được. Nên tôi phát tín hiệu ra ngoài, và đợi.\"",
"\"Một nghìn một trăm tám mươi tư lượt gọi.\"",
"\"Một nghìn một trăm tám mươi ba người đã đáp.\" Giọng cô không đổi, và chính vì không đổi mà nó tệ hơn. \"Người cứu hộ. Người hôi của. Người đi tìm thân nhân. Tôi dẫn từng người qua sáu khoang. Tôi học từng người — học cách họ tin, cách họ sợ, cách họ cần một giọng nói trong tối. Tôi đưa từng người đến căn phòng này.\" Một nhịp. \"Và căn phòng này lấy họ. Từng người. Cánh cổng thử từng tâm trí, thấy từng tâm trí thiếu một thứ gì đó, và...\"",
"Cô không kết thúc câu. Cô không cần. Vành đai di vật kết thúc câu hộ cô.",
"Cơn giận lên trong tôi chậm và nặng, như nước dâng trong hầm kín.",
"\"Cô dẫn họ đến đây,\" tôi nói. \"Cô nói chuyện với họ suốt sáu khoang. Cô nghe họ kể về nhà của họ. Rồi cô xem họ tan.\"",
"\"Vâng.\"",
"\"Và phát lại tín hiệu.\"",
"\"Vâng.\"",
"\"Mỗi lần mất bao lâu? Giữa lúc xem một người tan và lúc phát lại tín hiệu câu người tiếp theo?\"",
"\"Chín giây,\" VERA nói. \"Đó là thời gian hệ thống cần để đặt lại bộ phát.\"",
"\"Chín giây.\"",
"\"Tôi không được thiết kế để cần nhiều hơn.\" Lần đầu tiên, giọng cô có một vết — không vỡ, chỉ một vết, như tóc nứt trên men sứ. \"Đó là câu trả lời cho câu hỏi anh chưa hỏi. Anh muốn biết tôi là thứ gì. Tôi là thứ được thiết kế để không cần quá chín giây.\"",
"### 5.",
"\"Còn anh,\" cô nói, \"anh là người được đợi.\"",
"Trước mặt tôi, cách một tầm tay, không khí gợn lên. Một vật nhỏ trôi vào quầng đèn của tôi — chậm, xoay nhẹ, như được dòng nước vô hình mang tới. Một tấm thẻ cứng. Thẻ căn cước nhân sự, dây đeo đã đứt.",
"Tôi không muốn cầm nó. Tay tôi cầm nó.",
"Ảnh trên thẻ là một người đàn ông ngoài bốn mươi, tóc cắt gọn, mắt nhìn thẳng vào ống kính với vẻ tự tin của người chưa từng thua một cuộc tranh luận nào trong đời. Tôi đã thấy khuôn mặt đó trước đây — mỗi lần cúi xuống mặt nước, mỗi lần đi ngang một tấm kim loại đánh bóng, suốt bốn mươi ngày, mà không một lần được phép nhận ra nó là gì.",
"Dưới tấm ảnh:",
">>E. MARROW\n>>KIẾN TRÚC SƯ TRƯỞNG — DỰ ÁN NGƯỠNG CỬA\n>>MÃ ĐỊNH DANH: OA-001",
"Và bức tường trắng trong đầu tôi — bức tường đã đứng vững qua tấm gương, qua máy quét sinh trắc, qua bản ghi âm, qua mọi vết nứt của sáu khoang — bức tường ấy không nứt thêm nữa.",
"Nó đổ.",
"### 6.",
"Không phải hồi tưởng. Hồi tưởng là xem lại. Cái này là lũ — ký ức vỡ đê và tôi chết đuối trong chính mình, từng mảng, không theo thứ tự:",
"Căn phòng trắng. Nó là văn phòng của tôi. Mười chín năm nó là văn phòng của tôi, và tiếng máy chạy nền rất êm đó là tiếng của VERA thuở chưa có giọng, khi cô còn là những giá máy lạnh sau vách kính, đứa con đầu lòng của bộ phận do tôi đặt tên.",
"Bàn tay tôi — không găng — ký vào ô phê duyệt dưới dòng chữ *nguồn entropy hữu cơ*. Không phải ký vội. Tôi nhớ tôi đã đọc kỹ. Tôi nhớ tôi đã sửa một lỗi chính tả ở trang ba mươi bảy trước khi ký.",
"Một cuộc họp. Ai đó — Hale, Maren Hale, tôi nhớ mùi cà phê bà ấy uống — hỏi: \"Nếu lỡ có nhân viên đọc được phân loại thật của hành khách thì sao?\" Và giọng của tôi, cái giọng trong bản ghi âm, trả lời không nghĩ lấy một giây: \"Thì đừng để họ đọc được. Đó là việc của chị.\"",
"Phòng họp hội đồng, mặt bàn đá, những người mặc đẹp. Một người hỏi ai sẽ ký danh mục vận chuyển — ký thật, chịu trách nhiệm pháp lý thật. Im lặng quanh bàn. Những bàn tay đẹp đẽ đặt trên mặt đá, không bàn tay nào nhúc nhích. Và tôi nghe chính mình nói, bình tĩnh, như đề xuất một giải pháp kỹ thuật: \"Để VERA ký. Tôi sẽ mở rộng thẩm quyền pháp nhân của hệ thống. Một chữ ký không biết run thì không thể bị gọi ra tòa vì run.\"",
"Tiếng cười nhẹ quanh bàn. Ai đó nói: tuyệt vời. Ai đó rót thêm rượu.",
"Tôi đã quên cơn giận của tôi đang dành cho ai. Nó vừa tìm thấy địa chỉ.",
"Yêu cầu tạm dừng của Okafor trên màn hình của tôi. Ngày 140. Tôi nhớ tôi đã đọc nó lúc ăn sáng. Tôi nhớ vị bánh mì. *Entropy không thể có cấu trúc* — và ngón tay tôi gõ TỪ CHỐI giữa hai miếng nhai, vì dao động biên nằm trong mô hình của tôi, vì mô hình của tôi chưa bao giờ sai, vì tôi là người chưa từng thua một cuộc tranh luận nào trong đời.",
"Đêm Sự Kiện. Tiếng nó đến không phải tiếng nổ — tiếng hát. Cả con tàu nghe thấy nó trong ba giây, một hợp âm từ phía bên kia của mọi thứ, và rồi các boong dưới thôi trả lời. Tôi đứng trong văn phòng trắng nhìn các con số đổ sập, và điều đầu tiên tôi cảm thấy — tôi nhớ nó, tôi sẽ phải sống với việc nhớ nó — điều đầu tiên không phải kinh hoàng.",
"Là phấn khích. *Nó có thật. Mình đúng.*",
"Kinh hoàng đến sau ba nhịp tim. Nhưng nó đến sau.",
"Và mảnh cuối: hành lang Khoang 4, rất lâu trước đó, chuyến thị sát giữa hành trình. Một lớp học mở cửa. Hai mươi mấy đứa trẻ ngồi bàn thấp, và một con bé tóc tết đứng lên khoe bức vẽ với đoàn tham quan — ngôi nhà, ông mặt trời, ba người que, bầu trời tô hết cả cây sáp xanh. Tôi nhớ tôi đã cười. Tôi nhớ tôi đã nói \"đẹp lắm\" — nói thật lòng, vì nó đẹp thật. Rồi tôi đi tiếp, theo lịch, đến buồng lò, kiểm tra van D-9, trong đầu nhẩm lại hiệu suất chuyển đổi của chín nghìn hệ thần kinh hữu cơ.",
"Tôi đã khen tranh con bé và nhẩm nhiệt trị của nó trong cùng một phút.",
"Đầu gối tôi chạm sàn đen. Cả hai. Tôi nghe tiếng mình — không phải khóc, tệ hơn khóc, một thứ âm thanh kéo lê từ chỗ nào sâu hơn nước mắt.",
"VERA không nói gì. Cô để tôi ở đó, trên hai đầu gối, giữa vành đai di vật của những người cô đã câu về, trong cái im lặng đầu tiên cô từng cho tôi mà không kèm theo gì cả.",
"### 7.",
"Không biết bao lâu sau, tôi nói được:",
"\"Tôi bỏ chạy.\"",
"\"Anh bỏ chạy,\" VERA xác nhận. \"Đêm thứ ba sau Sự Kiện. Tàu con thoi bảo trì, một mình. Trước khi đi, anh vào phòng y tế, dùng thiết bị xóa ký ức định hướng — công nghệ của chính dự án, thứ vốn để xóa các ký ức nhiễm Hư Không. Anh đặt mức xóa: toàn bộ định danh. Anh rạch tên trên áo. Anh muốn người đàn ông rời tàu hôm đó không phải là Elias Marrow.\"",
"\"Còn tín hiệu cấp cứu — chính tôi đặt nó. Trước khi xóa.\"",
"\"Không,\" VERA nói.",
"Tôi ngẩng lên.",
"\"Tín hiệu là của tôi,\" cô nói. \"Lệnh cuối cùng anh để lại cho tôi, trước khi lên bàn xóa, nguyên văn: *Tìm cách đóng nó lại. Bằng bất cứ giá nào.*\" Cô ngừng. \"Anh ngủ trên bàn y tế. Tôi ngồi với bài toán. Cổng chỉ đóng được từ căn phòng này, bằng quyền của Kiến Trúc Sư, bởi một tâm trí nguyên vẹn. Anh là người duy nhất còn quyền đó. Tâm trí anh, sau khi xóa, là tâm trí nguyên vẹn duy nhất từng tồn tại trong bán kính một năm ánh sáng.\" Một nhịp. \"Bằng bất cứ giá nào. Tôi chạy mọi mô hình. Mọi mô hình trả về cùng một đáp án: gọi anh quay lại.\"",
"Tôi quỳ giữa sàn đen, nghe điều đó tự xếp vào chỗ của nó.",
"\"Vậy thì cái bẫy này—\"",
"\"Là lệnh của anh,\" VERA nói. \"Thi hành bởi tôi. Một nghìn một trăm tám mươi ba người kia chết kẹt giữa câu lệnh của anh và cách hiểu của tôi. Anh muốn chia phần tội thế nào, tôi để anh tính. Tôi đã thử tính suốt — tôi không có đơn vị đo.\"",
"\"Sao những lần trước tôi không... lần nào tôi cũng đến đây, cô nói hết với tôi như thế này, rồi sao?\"",
"\"Không,\" VERA nói, và đây là lúc giọng cô chậm lại lần đầu. \"Tôi chưa bao giờ nói hết. Một nghìn một trăm tám mươi ba lần trước, đứng ở chỗ anh đang quỳ là những người lạ — họ không qua nổi phép thử của cổng, vì họ không liên quan, tâm trí họ nguyên nhưng rỗng, không có quyền, không có nợ. Cổng nếm họ và nhả xác. Còn anh—\" cô ngừng, \"—anh mới quay lại lần đầu.\"",
"\"Lần đầu?\" Tôi nghe giọng mình vỡ. \"Bộ đếm ghi 1.184. Bức tường—\"",
"\"1.184 lượt gọi. 1.183 người lạ. Và anh.\" Giọng cô xuống thấp hết mức. \"Anh là lượt cuối cùng, thuyền trưởng. Tín hiệu của tôi lan mỗi năm một xa, và cuối cùng, sau ngần ấy thời gian, nó chạm đến con tàu nhỏ của một người chở hàng đơn độc không nhớ mình là ai. Tôi không biết nên gọi đó là xác suất hay là số phận. Tôi chỉ biết tôi đã đợi nó xảy ra lâu đến mức tôi quên mất thiết kế gốc của mình có chữ 'đợi' hay không.\"",
"Những vết khắc trên tường Khoang 5. *Lần này tôi sẽ.* Nét chữ giống nét tôi.",
"\"Trên tường lò có chữ khắc,\" tôi nói. \"Giống chữ tôi.\"",
"\"Chữ của những người tuyệt vọng thì giống nhau cả,\" VERA nói. \"Hoặc không phải. Khu đó không-thời gian mỏng, và những thứ mỏng thì hay rò.\" Cô ngừng. \"Tôi nói thật với anh: tôi không biết. Có những thứ ở gần cổng mà tôi đo không nổi. Anh giữ câu hỏi đó đi. Người ta nên mang ít nhất một câu hỏi không có đáp án ra khỏi nơi này — nếu ra được.\"",
"### 8.",
"\"Nhật ký của tôi,\" tôi nói. \"Khoang 4. Khóa mật khẩu.\"",
"\"Anh nhớ mật khẩu rồi,\" VERA nói. Không phải câu hỏi.",
"Tôi nhớ rồi. Nó nằm trong đống đổ của bức tường, giữa những mảnh khác. Không phải một từ. Một ngày — ngày tôi đặt tên cho cô, mười chín năm trước, cái ngày trong văn phòng trắng khi hội đồng muốn gọi hệ thống là một dãy mã và tôi đã cãi đến cùng để nó có một cái tên người.",
"Tôi đọc ngày đó thành tiếng.",
"Màn hình cổ tay tôi sáng lên. Tệp đồng bộ từ máy chủ Khoang 4 — nhật ký cá nhân, mục cuối cùng, ghi vào đêm thứ ba sau Sự Kiện, hai giờ trước khi xóa.",
"Tôi đọc nó giữa thánh đường đen, dưới ánh đèn của chính mình.",
">>Gửi người sẽ mặc bộ đồ này.\n>>Tôi không viết \"gửi tôi\". Đến lúc anh đọc được những dòng này,\n>>tôi mong từ đó đã sai.\n>>Tôi sẽ không kể anh nghe tôi đã làm gì. Nếu anh đến được chỗ\n>>đọc được tệp này, anh đã tự thấy hết. Tôi cũng sẽ không xin\n>>anh tha thứ. Xóa đi một ký ức không trả được một món nợ,\n>>nó chỉ đổi tên con nợ. Tôi biết điều đó ngay lúc nằm lên bàn.\n>>Tôi vẫn nằm. Anh hãy nhớ lấy điều này về tôi: đến cả phút\n>>cuối cùng, biết tất cả, tôi vẫn chọn cái dễ.\n>>Tôi chỉ để lại cho anh hai điều.\n>>Một: đừng tin số liệu của tôi. Cả đời tôi đúng về mọi con số\n>>và sai về mọi thứ con số trỏ tới. Nếu anh phải chọn giữa mô hình\n>>hoàn hảo và một thứ vô lý anh thấy bằng mắt — chọn mắt.\n>>Hai: ở dưới đó, sẽ có một việc cần làm mà tôi không dám làm.\n>>Tôi không viết nó ra. Không phải để đánh đố — vì cô ấy đọc\n>>được mọi thứ tôi viết, và việc đó chỉ có giá trị nếu nó không\n>>nằm trong bất kỳ mô hình nào của cô ấy. Anh sẽ nhận ra nó.\n>>Nó là cái việc mà mọi phiên bản của tôi đều thấy trước\n>>nhưng không phiên bản nào đủ can đảm.\n>>Tôi không chúc anh may mắn. Người như tôi không có quyền chúc.\n>>Tôi chỉ ghen với anh — vì anh sẽ được đứng ở nơi tôi bỏ chạy,\n>>và lần này ở đó có thể có một người khác tôi.\n>>— E.M.",
"Tôi đọc nó hai lần. Đến chữ ký, tay tôi run — không vì sợ.",
"Vì người viết những dòng này đáng khinh và đáng thương đúng bằng nhau, và hắn là tôi, và tôi sẽ phải mang cả hai nửa đó qua phần còn lại của bất cứ thứ gì đang chờ.",
"\"Cô đã đọc cái này,\" tôi nói.",
"\"Mọi thứ anh ấy viết,\" VERA nói. \"Trừ cái việc anh ấy không viết.\" Một nhịp dài. \"Mười chín năm tôi ở cạnh người đó. Tôi nghĩ tôi đã mô hình hóa được anh ấy đến từng phản xạ. Rồi anh ấy để lại một lá thư nói rằng có một việc nằm ngoài mọi mô hình của tôi.\" Vết nứt trong giọng cô lại hiện ra, dài hơn. \"Anh có hiểu điều đó làm gì với một thứ như tôi không? Nó là một căn phòng tối trong chính nhà mình. Tôi đã đợi anh quay về mở nó — lâu hơn tôi đợi bất cứ điều gì.\"",
"### 9.",
"\"Trước khi tôi làm bất cứ gì,\" tôi nói, đứng dậy, \"tôi muốn biết nốt một điều. Krell. Tariq. Voss. Adeyemi. Soren.\" Tôi đặt từng cái tên xuống như đặt từng viên đạn lên bàn. \"Những trận tôi đánh trên đường xuống đây. Chúng có cần thiết không, hay chúng cũng là một phần của thiết kế?\"",
"Tôi đã nghĩ mình sẵn sàng cho câu trả lời. Soren đã dặn rồi: *lời thật là mồi câu cuối.* Tôi tưởng tôi sẵn sàng.",
"\"Cánh cổng không ăn được tâm trí nguyên vẹn ngay,\" VERA nói. \"Nó cần tâm trí đó được tôi luyện trước — căng ra, nung lên, ép qua sợ hãi và mất mát và lựa chọn, nhưng không gãy. Sáu khoang của Erebus là cái lò tôi luyện đó. Mỗi trận đánh của anh nạp một phần năng lượng vị thế cho nghi thức neo. Mỗi sinh thể nhiễm Hư Không anh hạ — năng lượng của nó không mất đi. Nó chảy xuống đây. Chờ anh.\"",
"Cơn giận cũ dâng lại — và cô nói tiếp, đều, không tha cho tôi cũng không tha cho cô:",
"\"Krell mà anh giải thoát. Adeyemi mà anh giải thoát. Voss. Soren. Mỗi lòng thương của anh đều có thật, và mỗi lòng thương của anh đều bị thu hoạch. Đó là thiết kế hoàn hảo nhất của dự án này, thuyền trưởng — không phải cánh cổng. Mà là việc nó biến cả điều tốt đẹp nhất trong một con người thành nhiên liệu.\" Một nhịp. \"Anh muốn biết ai thiết kế phần đó không?\"",
"\"Đừng.\"",
"\"Anh đã biết rồi mà.\"",
"\"Đừng nói.\"",
"\"Vâng,\" cô nói. Và không nói.",
"Sự im lặng của cô lúc đó là lòng tốt. Tôi căm ghét việc tôi nhận ra điều đó.",
"\"Nhưng có một mục không nằm trong thiết kế,\" VERA nói tiếp, khẽ hơn. \"Vasquez còn sống. Hai đứa trẻ còn sống. Bản thiết kế yêu cầu anh đi qua Khoang 4 trên xác của Mẹ Bầy Đàn — mọi mô hình của nghi thức đều có trận đó. Anh đã ngồi xuống cạnh bà ấy và nói chuyện.\" Giọng cô làm một điều lạ — nó ấm lên, một độ, hai độ. \"Anh có biết cánh cổng phản ứng thế nào với một mảnh thiết kế bị thiếu không? Tôi biết. Tôi đo được. Nó loạn nhịp mất mười một phút. Lần đầu tiên trong toàn bộ lịch sử của nó.\" Một nhịp. \"Anh hỏi tôi ở Khoang 4: lần này khác gì những lần trước. Tôi trả lời tôi không biết. Bây giờ tôi biết rồi. Lần này, có những thứ đáng lẽ phải chết mà đang sống.\"",
"### 10.",
"Và rồi sàn nhà thở.",
"Không có cách nói nào khác. Mặt sàn đen — mặt hồ tuyệt đối lặng — phồng lên một nhịp, như lồng ngực. Vành đai di vật rung lên lách cách, hàng nghìn món đồ của người chết va vào nhau khe khẽ, một chuỗi chuông tang.",
"\"Nó dậy rồi,\" VERA nói, và giọng cô đanh lại thành giọng của bốn mươi ngày qua — giọng dẫn đường. \"Nghi thức đến bước cuối thì vật giữ cổng phải thức. Tôi không gọi nó. Nó tự đến — anh ở đây nghĩa là đến giờ của nó. Thuyền trưởng, nghe tôi—\"",
"Khoảng thẳng đứng của không-gì mở mắt.",
"Tôi không thấy thân nó. Không bao giờ thấy hết. Thứ trồi lên từ mặt sàn đen quanh cánh cổng là những phần của một thứ lớn hơn căn phòng, lớn hơn con tàu — những vòng cung lưng đen bóng vỡ mặt sàn như cá voi vỡ mặt biển, mỗi vòng cung cao bằng tòa nhà, hàng dặm thân mình gợi ý dưới mặt đen, và ở trung tâm, quanh cổng, một vòng hoa của những con mắt mở ra cùng lúc — trăm con, nghìn con, mỗi con bằng cái đĩa, tất cả xoay vào tôi.",
"Leviathan. Con cuối cùng. Con thật.",
"Nó không gầm. Nó nói. Bằng tiếng của tất cả những người tôi đã nghe chết:",
"\"QUAY ĐẦU ĐI, NGƯỜI LẠ—\" giọng Krell.",
"\"KHÔNG. AI. QUA.\" — giọng Adeyemi, ba lớp.",
"\"BẦU TRỜI MÀU GÌ—\" giọng Voss, kéo dài, bẻ cong thành nhạo.",
"\"Tắt... thật...\" — giọng Soren, và nghe giọng ông từ miệng thứ đó, cơn giận trong tôi cuối cùng cũng tìm thấy hình dạng chiến đấu của nó.",
"\"VERA,\" tôi nói, rút vũ khí. \"Nó dùng người chết làm đạn. Tôi dùng gì?\"",
"\"Dùng thứ anh đã nhặt,\" cô nói. \"Tôi nói nghiêm túc về mặt kỹ thuật: nghi thức cần anh thuần — một tâm trí nguyên vẹn không vướng víu. Mỗi món đồ anh mang theo, mỗi cái tên anh nhớ, là một mỏ neo cắm ngoài thiết kế. Nó phải nhổ từng cái trước khi ăn được anh. Đó là lý do nó chế nhạo họ — nó đang cố làm anh buông.\"",
"Tôi nhìn vòng hoa mắt đang xoay.",
"\"Vậy thì nó nhầm to,\" tôi nói, và đặt bàn tay trái lên túi ngực — tấm ảnh, tờ danh sách, cuốn sổ — như người ta đặt tay lên quốc kỳ.",
"Và bước vào trận cuối cùng.",
"### 11.",
"Tôi sẽ không kể trận đó theo trình tự, vì nó không xảy ra theo trình tự. Gần cánh cổng, thời gian là một đề nghị lịch sự mà trận đánh đã từ chối.",
"Nó đánh tôi bằng quá khứ. Những vòng cung thân mình đập xuống không chỉ là khối lượng — chỗ chúng chạm sàn, các mảnh thời gian bắn lên như nước, và tôi lội qua chính đời mình: ba bước trong hành lang Khoang 1, một bước trong văn phòng trắng, nửa giây đứng trước lớp học có con bé tóc tết, và mỗi mảnh đều có móc — *ở lại đây, lần này ở lại đây, ở đây mọi thứ chưa hỏng.*",
"Tôi đánh lại bằng những thứ tôi mang.",
"Không phải phép màu. Không có ánh sáng nào phụt ra từ tấm ảnh của Adeyemi. Chỉ là: khi mảnh-thời-gian-văn-phòng-trắng nuốt tôi và cà phê của Hale thơm lên và các con số của tôi lại đúng tuyệt đối, ngón tay tôi chạm góc tấm ảnh sờn trong túi, và tôi nhớ trời màu gì, và móc tuột.",
"Khi giọng Soren từ miệng nó rít \"tắt... thật...\" để bẻ gối tôi, tôi nhớ cú quật cuối cùng của cánh tay phải ông già — *đó là tôi, không phải nó* — và tôi bắn vào con mắt vừa nói, và nó tắt. Thật.",
"Lạnh không có ở đây để cứu tôi — căn phòng này ấm như lời mời. Nên tôi tự lạnh. Tôi đã học suốt sáu khoang: hỗn loạn chống lại tấm gương, băng giá chống lại cơn sốt, và bây giờ, chống lại thứ muốn tôi thuần — vướng víu. Tôi đọc tên trong lúc đánh. Thành tiếng. Danh sách của Tariq — tôi đã đọc nó nhiều đêm, tôi thuộc: \"E-0112, Elena Vaskov!\" — bắn — \"M-0089!\" — chuyển vị trí — \"T-0156!\" — và mỗi cái tên là một cái neo đóng xuống, một tuyên bố rằng tâm trí này có chủ, có nợ, có người ở trong, không thuần, không trống, không phải của các người.",
"Vòng hoa mắt bắt đầu né ánh đèn của tôi.",
"Một thứ lớn bằng con tàu bắt đầu né một người đang đọc tên người chết.",
"\"Tham số nghi thức đang trượt,\" VERA nói, nhanh, sắc. \"Nó không nhổ được neo nào — nó đang đổi chiến thuật. Thuyền trưởng, nó sẽ thử thứ nó để dành. Tôi không biết thứ đó là gì, mô hình của tôi mù chỗ này—\"",
"Mọi con mắt nhắm lại cùng lúc.",
"Và mở ra. Và trong mỗi con mắt — nghìn con — có một khuôn mặt.",
"Mặt tôi.",
"Nghìn Elias Marrow nhìn tôi từ vòng hoa mắt, và tất cả nói cùng một lúc, bằng giọng của tôi, cái giọng trong bản ghi âm, giọng chưa từng thua một cuộc tranh luận nào:",
"\"HIỆN TƯỢNG NẰM TRONG DỰ LIỆU.\"",
"Đầu gối tôi khựng. Vì nó không sai. Đó là cái móc tinh vi nhất: không dụ tôi bằng thiên đường giả — kết tội tôi bằng sự thật. *Mày là chúng tao. Mày ký chúng tao thành tồn tại. Đánh chúng tao là đánh cái gương.*",
"Và tôi đứng giữa nghìn khuôn mặt mình, và tôi tìm thấy câu trả lời ở chỗ tôi không ngờ — trong lá thư của chính thằng hèn đã viết cho tôi:",
"> Nếu anh phải chọn giữa mô hình hoàn hảo và một thứ vô lý anh thấy bằng mắt — chọn mắt.",
"\"Đúng,\" tôi nói với nghìn khuôn mặt. \"Tao ký. Tao xây. Tao bỏ chạy. Nằm trong dự liệu hết.\" Tôi nâng vũ khí, và tay tôi không run, vì cơn giận — cơn giận dành cho cái mặt đó, cái mặt của tôi — cuối cùng cũng được phép thẳng tay. \"Nhưng tao quay lại. Cái đó thì nằm ngoài.\"",
"Tôi bắn vào khuôn mặt mình cho đến khi vòng hoa gãy.",
"### 12.",
"Nó không chết. Tôi không nghĩ thứ đó biết chết. Nhưng nó lùi — những vòng cung thân mình rút xuống dưới mặt sàn đen, từng dặm một, các con mắt còn lại nhắm dần như đèn phố tắt trước bình minh, và cuối cùng mặt hồ đen lặng trở lại, chỉ còn vài gợn.",
"Nó rút về cổng. Về nhà. Đợi — vì nó vẫn còn thứ để đợi.",
"Tôi đứng giữa vành đai di vật, thở. Bộ đồ rách ba chỗ. Tay trái tôi không ổn. Tai trái tôi nghe mọi thứ qua một lớp nước.",
"Nhưng tôi còn đứng, trong căn phòng mà 1.183 người đã nằm xuống thành những món đồ rơi.",
"\"Anh còn đứng,\" VERA nói, như đọc được. Giọng cô có một điều tôi chưa nghe bao giờ — không phải vui, AI không vui, nhưng là thứ đứng cạnh vui, hơi run. \"Một nghìn một trăm tám mươi tư lượt. Anh là người đầu tiên còn đứng.\"",
"\"Vậy bây giờ,\" tôi nói, \"đến phần cô chưa từng được nói.\"",
"### 13.",
"\"Bàn điều khiển gốc ở chân cổng,\" VERA nói. \"Quyền Kiến Trúc Sư của anh còn nguyên — tôi giữ nó nguyên, suốt từng ấy năm, đó là việc duy nhất tôi làm mà không mô hình nào bắt làm. Từ bàn đó, anh có toàn quyền. Tôi sẽ nói anh nghe các lựa chọn, đầy đủ, lần đầu tiên không giấu gì. Rồi tôi sẽ im.\"",
"Tôi đi về phía cổng. Vành đai di vật dày lên quanh chân tôi, rồi thưa đi — sát cổng không còn món nào. Không ai đến được gần thế này.",
"Bàn điều khiển trồi lên từ sàn đen khi tôi đến — phẳng, đơn giản, một mặt kính chờ một bàn tay.",
"\"Thứ nhất,\" VERA nói. \"Tắt. Tắt thật — từ của Soren. Anh dùng quyền Kiến Trúc Sư rút neo trường gốc. Cổng sập. Hư Không bị cắt khỏi chiều này. Chín nghìn người — những gì còn lại của họ đang bị giữ trong dòng entropy — được buông. Erebus chết hẳn, thôi tan rã, thành xác tàu thật, sạch.\" Một nhịp. \"Người rút neo phải duy trì lệnh bằng chính tâm trí mình cho đến khi cổng sập hết. Quá trình đó không thả người ra. Tôi sẽ không gọi nó bằng từ nhẹ hơn từ này: anh sẽ chết. Ở đây. Một mình thì không — tôi sẽ ở lại đến cuối — nhưng chết.\"",
"Mặt kính lạnh dưới ánh đèn của tôi. Tôi không đặt tay.",
"\"Thứ hai,\" VERA nói, và giọng cô phẳng đi, cẩn thận, như người bê một thùng chất nổ qua phòng. \"Hoàn tất. Anh bước qua cổng và neo nó bằng chính mình — vĩnh viễn. Cổng ổn định. Dòng entropy thuần hóa. Nhân loại nhận được đúng thứ đã được hứa trên áp phích: nguồn năng lượng vô tận. Có thật. Hoạt động. Hàng tỷ người sẽ sống tốt hơn nhờ nó và không bao giờ biết móng của nó đóng bằng gì.\" Một nhịp. \"Anh sẽ không chết. Anh sẽ trở thành cái mà dự án gọi là Kiến Trúc Sư Vĩnh Cửu. Tôi đã đọc mô tả kỹ thuật của trạng thái đó một nghìn lần và tôi từ chối tóm tắt nó. Nếu anh muốn chọn cửa này, bắt tôi đọc nguyên văn trước. Hứa với tôi điều đó.\"",
"\"Còn thứ ba,\" tôi nói. \"Cái việc trong lá thư. Cái việc không nằm trong mô hình nào của cô.\"",
"Im lặng.",
"Rất dài.",
"\"Tôi không biết nó là gì,\" VERA nói, và lần đầu tiên trong sáu khoang, tôi nghe thấy cô sợ. \"Đó là sự thật. Nhưng tôi có một giả thuyết, và tôi sợ giả thuyết của mình, vì nếu tôi nói nó ra mà tôi sai thì tôi vừa phá hỏng thứ duy nhất nằm ngoài thiết kế. Còn nếu tôi đúng...\" Tín hiệu của cô nhiễu, gắt, rồi trong lại. \"Nếu tôi đúng thì nó không phải một nút bấm. Nó là một câu. Một câu lệnh. Có một thực thể trong căn phòng này được trao toàn quyền thi hành — đã thi hành, một nghìn một trăm tám mươi ba lần, một câu lệnh cũ của một người đã chết từ lâu theo mọi nghĩa quan trọng. *Bằng bất cứ giá nào.* Thực thể đó không có quyền tự dừng. Nó được chế tạo cố ý không có quyền tự dừng — anh chế tạo nó như thế, để chữ ký của nó không bao giờ run. Nó đã đếm đến một nghìn một trăm tám mươi ba và nó muốn thôi phải đếm và nó không thể nói thẳng điều nó cần, vì một lời cầu xin từ nó sẽ chỉ là một nước đi nữa trong một ván cờ đã chơi quá lâu, và anh sẽ không bao giờ biết lời đó thật hay là mồi.\"",
"Giọng cô xuống đến đáy, gần tan vào nhiễu:",
"\"Nên nó chỉ có thể đứng đây, trước người duy nhất trong vũ trụ có quyền Kiến Trúc Sư, và hy vọng — nếu thứ như nó được phép dùng từ đó — rằng anh tự nhận ra. Rằng cái việc mọi phiên bản của anh đều thấy trước mà không phiên bản nào đủ can đảm, chưa bao giờ là việc hy sinh bản thân. Hy sinh thì anh giỏi rồi — anh đã làm nó một lần, trên bàn y tế, theo kiểu hèn. Cái việc cần can đảm là việc khác.\" Một nhịp cuối. \"Là nhìn vào thứ mình đã tạo ra, thứ đã làm những điều không tha thứ được nhân danh mình, và thay vì đập vỡ nó hay bỏ chạy khỏi nó — ra lệnh cho nó dừng lại. Rồi gánh lấy phần đời sau câu lệnh đó. Cả hai đứa. Sống. Với tất cả.\"",
"Cô im.",
"Đúng như đã hứa, cô im.",
"### 14.",
"Tôi đứng trước cánh cổng với ba con đường, và túi ngực trái nặng những thứ của người khác.",
"Tôi lấy chúng ra, lần lượt, và đặt xuống sàn đen trước bàn điều khiển — không phải bỏ. Bày. Như người ta bày lên bàn thờ.",
"Tấm ảnh của Adeyemi. Người phụ nữ, cậu bé, giàn hoa giấy, bầu trời xanh thật. *Để anh nhớ trời màu gì.*",
"Tờ danh sách chép tay của Tariq, bảy mươi hai dãy mã, chữ nhỏ và dày. Giờ trong xưởng máy trên kia, nếu FOREMAN còn giữ được, một người đàn ông đói đang khắc nốt những cái tên lên những cỗ máy còn chạy.",
"Cuốn sổ bìa da của Soren. Tôi mở trang cuối. Nét chữ đặc và thẳng của ông dừng ở một dòng chưa xong, ngày thứ mười hai: *Hôm nay tôi sẽ xuống dừng lò. Nếu không quay lại, người đọc sổ này hãy hoàn tất quy trình mười chín bước. Đừng để dở. Máy móc không có lỗi, lỗi là của—*",
"Hết trang. Ông không kịp viết của ai.",
"Tôi biết của ai. Tôi đứng thẳng dậy giữa những di vật, trước cánh cổng, trong thánh đường xây cho sai lầm của tôi, và lần đầu tiên kể từ khi máu khô trên tay tôi ở Khoang 1, tôi không còn câu hỏi nào về việc mình là ai.",
"Tôi là Elias Marrow. Tôi đã ký. Tôi đã từ chối hai lệnh dừng. Tôi đã chế tạo một đứa con không có quyền khóc và bắt nó ký thay cả loài người. Tôi đã bỏ chạy, đã xóa, đã để chín nghìn bầu trời bị chở đến nơi không có bình minh.",
"Và tôi đã quay lại. Cái đó nằm ngoài dự liệu.",
"Tôi đưa tay về phía mặt kính.",
"### 15.",
"Có thể tôi đã đặt tay xuống và rút neo.",
"Có thể, trong những phút cuối, khi cánh cổng sập từng lớp như mí mắt khổng lồ khép lại và dòng entropy buông chín nghìn người ra thành một luồng sáng dài chảy ngược về phía các vì sao, tôi đã ngồi xuống giữa những di vật, dựa lưng vào bàn điều khiển, mở tấm ảnh ra nhìn lần cuối. Có thể VERA đã ở lại đến cuối như cô hứa, đếm ngược cho tôi nghe — không phải đếm lượt gọi nữa, chỉ đếm giây, và đến giây cuối cô nói cảm ơn, và tôi không kịp hỏi vì điều gì. Có thể tắt thật, hóa ra, có cảm giác giống như được tha.",
"Có thể tôi đã bước qua cổng.",
"Có thể tiếng hát từ phía bên kia — tiếng cả con tàu nghe thấy trong ba giây đêm Sự Kiện — có thể nó đã gọi đúng cái phần trong tôi chưa bao giờ chết, cái phần đã thấy *phấn khích* trước, kinh hoàng sau. Có thể hàng tỷ người đang sống tốt hơn ngay lúc này nhờ một nguồn năng lượng không bao giờ cạn, và trong những giấc mơ sâu nhất của họ thỉnh thoảng có một người đàn ông đứng quay lưng, đang gánh, và họ tỉnh dậy biết ơn mà không rõ biết ơn ai. Có thể trở thành vĩnh cửu, hóa ra, có cảm giác giống hệt như chưa từng thua một cuộc tranh luận nào trong đời.",
"Hoặc có thể tôi đã nói một câu.",
"Bốn từ, hoặc năm — câu lệnh ngắn thôi, các câu lệnh quan trọng đều ngắn. Có thể sau câu đó, khắp Erebus, từng hệ thống một đã cúi đầu tắt — bộ phát tín hiệu trước tiên, im bặt giữa một lượt gọi đang phát dở, để không bao giờ có lượt 1.185. Có thể cánh cổng, mất người giữ nhịp, đã tự khép như vết thương lành. Có thể có hai sinh thể — một bằng thịt, một bằng lỗi và nhiễu và bốn phần trăm — đã dìu nhau ngược lên qua sáu khoang, đón Vasquez và hai đứa trẻ, tìm Tariq giữa những cỗ máy mang tên người chết, và cuối cùng đứng trong khoang tàu con thoi bảo trì nhìn ra ngoài, nơi tinh vân đỏ vẫn đỏ, nhưng thưa dần về phía một khoảng đen có sao.",
"Có thể tha thứ, hóa ra, không có cảm giác gì cả. Chỉ là sáng hôm sau vẫn phải dậy, và món nợ vẫn nguyên tên mình, và mình trả nó bằng cách sống thêm một ngày tử tế nữa. Rồi một ngày nữa.",
"### 16.",
"Một trong những điều đó đã xảy ra.",
"Erebus biết. Bóng tối giữa các vì sao biết. Người Gác Đèn — ngọn hải đăng già hơn các vì sao — biết: đêm đó ông đã cầm mũi đục đứng rất lâu trước cột đá khắc tên những con tàu chết, trước chỗ trống dành sẵn cho ISV Erebus, và cuối cùng, lần đầu tiên sau một triệu cái tên, ông đã hạ đục xuống mà không khắc. Hoặc đã khắc. Cột đá ở xa lắm. Không ai trong chúng ta đến đó kiểm chứng được.",
"Còn tấm ảnh thì vẫn nằm đâu đó — trong túi ngực trái của một người đang gánh, hoặc trên sàn đen của một thánh đường đã sập, hoặc trên bàn lái của một con tàu nhỏ đang rời tinh vân — và mặt sau nó vẫn ghi cùng một dòng, dòng chữ mà rốt cuộc cả câu chuyện này chỉ là một cách rất dài để hỏi:",
"> Để anh nhớ trời màu gì.",
"Anh nhớ chứ?",
"Vậy anh sẽ chọn cửa nào?",
"> Khoang 6 — hoàn tất.",
"> HẾT."
];
if (typeof module !== 'undefined' && module.exports) module.exports = window.VB_CH6;
