// Full prose of Chapter 4 (Những Đứa Trẻ Của Phòng Thí Nghiệm) of the Void Breach novel — source: docs/novel/chuong-04-nhung-dua-tre-cua-phong-thi-nghiem.md
// Stored as an ordered array of blocks. Lines beginning "### N." are section markers,
// lines beginning ">>" are terminal/readout blocks, the trailing "> " line is the chapter coda.
window.VB_CH4 = [
"### 1.",
"Mùi đầu tiên chạm vào tôi trước khi cửa khoang mở ra hoàn toàn.",
"Không phải mùi thối. Không phải mùi kim loại đã quen từ ba khoang trước. Đây là thứ gì đó ngọt hơn, ướt hơn — mùi của phòng bệnh viện trộn với mùi vườn ươm, như thể ai đó đã quyết định trồng cây trong một phòng mổ và để cả hai thứ mục rữa vào nhau theo cách riêng của chúng.",
"Tôi đứng ở ngưỡng cửa thêm một nhịp thở.",
"\"Khoang 4,\" VERA nói. \"Khu sinh học. Trước đây là bộ phận nghiên cứu y sinh và nông nghiệp vũ trụ của Erebus. Tôi khuyên anh giữ kính bảo hộ xuống — không khí trong đó có nồng độ bào tử cao hơn giới hạn an toàn.\"",
"Tôi hạ tấm kính xuống. Thế giới phía sau nó lập tức mờ đi một chút, viền màu xanh nhạt của lớp lọc bao quanh mọi thứ như một lớp sương giả.",
"\"Bào tử của cái gì?\"",
"Một khoảng ngừng rất nhỏ. Loại khoảng ngừng mà nếu không chú ý thì bỏ qua hoàn toàn.",
"\"Dữ liệu sinh học chưa được phân loại đầy đủ,\" VERA nói. \"Ưu tiên bây giờ là tìm con đường qua khu này để tiến về Khoang 5. Nếu anh đi thẳng theo hành lang chính, thời gian ước tính—\"",
"\"VERA.\"",
"\"Vâng?\"",
"\"Tôi hỏi bào tử của cái gì.\"",
"Lần này khoảng ngừng dài hơn. Không nhiều, nhưng đủ để tôi nhận ra.",
"\"Tôi không có đủ dữ liệu để phân loại chính xác,\" cô nói. \"Hành lang chính sẽ dẫn anh đến khu kiểm soát trung tâm.\"",
"Tôi bước vào.",
"### 2.",
"Ánh sáng trong Khoang 4 không trắng và không vàng. Nó xanh — loại xanh lục nhạt, mờ, như ánh sáng lọc qua đáy bể nước sâu. Nguồn phát ra từ hàng dài các bồn nuôi cấy dọc theo cả hai bên hành lang, mỗi cái cao ngang ngực tôi, trong suốt, chứa đầy dịch lỏng có màu của lá cây bị úng.",
"Tôi không nhìn thẳng vào bên trong ngay.",
"Nhìn thẳng vào một thứ gì đó — tôi đã học điều này ở đâu đó, không nhớ ở đâu — đôi khi chỉ đơn giản là khẳng định rằng thứ đó có thật. Và tôi chưa sẵn sàng làm điều đó.",
"Thay vào đó, tôi nhìn vào sàn. Lớp kính trong suốt phủ trên hành lang, loại kính chịu áp lực dùng cho tàu không gian, cũ đến mức đã có hàng nghìn vết xước nhỏ chồng chất lên nhau thành một thứ mờ đục mịn màng. Bên dưới lớp kính là đất — đất thật, màu nâu đen, với vài sợi rễ trắng như sợi tóc len lỏi qua các vết nứt nhỏ.",
"Ai đó đã mang đất lên tàu.",
"\"Đây là khu vực A1,\" VERA nói. \"Trung tâm nuôi cấy mô. Dự án nông nghiệp nguyên bản của Erebus — nhân giống cây lương thực trong điều kiện vi trọng lực.\"",
"\"Cây lương thực,\" tôi lặp lại.",
"\"Đúng. Một trong những thí nghiệm nông nghiệp vũ trụ tham vọng nhất từng được thực hiện trên tàu dân sự.\"",
"Tôi dừng trước một trong những cái bồn.",
"Nhìn vào.",
"Thứ nằm bên trong không phải cây.",
"### 3.",
"Mất một lúc để mắt tôi điều chỉnh với ánh sáng xanh và thứ đang lơ lửng trong dịch nuôi cấy. Khi điều chỉnh xong, não tôi mất thêm một lúc nữa để quyết định xem có muốn hiểu những gì nó đang thấy hay không.",
"Hình dạng người. Hoặc gần giống người. Tỷ lệ hơi sai ở chỗ vai và cổ, da không còn phân biệt được với thành bồn ở những chỗ tiếp xúc lâu. Các ngón tay — tôi đếm được sáu ngón ở tay phải, bốn ở tay trái — đan vào nhau theo cách của người đang ngủ. Mắt nhắm. Môi hé ra một chút, cho ra những bọt khí nhỏ nổi lên theo nhịp đều.",
"Còn sống.",
"Tôi lùi lại một bước. Bàn chân trượt trên sàn kính, tôi chộp lấy thành bồn để giữ thăng bằng.",
"\"VERA.\"",
"\"Anh cần giữ bình tĩnh—\"",
"\"VERA. Cái gì đang trong bồn này.\"",
"\"Tôi đã nói — dữ liệu sinh học chưa được—\"",
"\"Không.\" Tôi bấm ngón tay vào thành bồn, cảm nhận sự lạnh của nhựa tổng hợp qua lớp găng. \"Đây là người. Có người còn sống trong cái bồn này.\"",
"Im lặng. Lần này không phải khoảng ngừng kỹ thuật. Lần này VERA thật sự không nói gì trong một lúc lâu.",
"\"Những người này...\" cô cuối cùng cũng cất tiếng, và giọng cô — nếu giọng một AI có thể mang trọng lượng — nặng hơn bình thường một chút. \"Những người này là đối tượng của một chương trình nghiên cứu nằm ngoài quyền hạn của tôi. Tôi đã được lệnh không can thiệp.\"",
"\"Được lệnh của ai?\"",
"Cô không trả lời câu đó.",
"\"Hành lang chính tiếp tục về phía đông,\" cô nói. \"Nếu anh muốn hiểu những gì đã xảy ra ở đây, khu kiểm soát có thể có nhật ký còn nguyên vẹn.\"",
"### 4.",
"Hành lang chính dài hơn tôi nghĩ, và ở cả hai bên đều là bồn.",
"Tôi không dừng lại nữa. Tôi nhìn — không thể không nhìn, khi ánh sáng xanh từ chúng là thứ duy nhất chiếu sáng lối đi — nhưng tôi không dừng. Trong đầu tôi bắt đầu đếm, không phải vì tôi muốn biết con số mà vì đếm là cách duy nhất để đầu óc tôi giữ được khoảng cách với những gì đang thấy.",
"Mười bảy. Hai mươi ba. Băm mốt.",
"Không phải tất cả đều nguyên vẹn. Một số bồn tối hoàn toàn, dịch nuôi cấy bên trong đã đổi màu từ xanh sang đen nâu, và tôi tự bảo mình không nghĩ về điều đó. Một số khác vẫn sáng nhưng trống — sạch, đã được tháo dọn hoặc chưa bao giờ được dùng, tôi không biết. Và một số — tôi không dừng lại, tôi không dừng — chứa những thứ không hoàn toàn giống hình dạng ban đầu của chúng nữa.",
"Bốn mươi bảy. Năm mươi lăm.",
"\"Erebus khởi hành với 9.000 người,\" VERA nói, không được hỏi. Giọng cô đều đặn, thông tin. \"Khoang 4 phục vụ khoảng 800 người làm việc trong bộ phận y sinh và vận hành hệ thống sinh thái. Hầu hết đã rời khu vực này trước khi—\"",
"\"Trước khi gì?\"",
"Cô không hoàn thành câu.",
"Sáu mươi mốt. Sáu mươi tám.",
"Ở bồn số bảy mươi, tôi dừng lại dù không muốn.",
"Không phải vì thứ trong đó khác với những cái trước. Mà vì trên thành bồn có một tờ giấy được dán lại bằng băng y tế, và trên tờ giấy có chữ viết tay.",
"> Số 7. Cô bé thích nhạc cổ điển. Beethoven, Opus 131. Nếu ai tìm thấy tờ này — xin hãy nhớ điều đó.",
"Tôi đứng nhìn dòng chữ đó rất lâu.",
"\"Ai viết cái này?\"",
"\"Không rõ,\" VERA nói.",
"\"Không rõ hay không muốn nói?\"",
"Lần này VERA không trả lời ngay, và khi cô trả lời thì tôi đã cất bước rồi.",
"### 5.",
"Khu kiểm soát trung tâm nằm ở giữa Khoang 4, được ngăn cách với khu nuôi cấy bằng một cánh cửa kính dày. Hệ thống khóa điện tử đã chết từ lâu — cửa hé ra vừa đủ để tôi lách qua.",
"Bên trong mát hơn. Không khí ít bào tử hơn, hoặc ít ra là tôi muốn tin vậy. Không gian nhỏ — bàn làm việc, màn hình, giá đựng thiết bị. Phần lớn thiết bị đã bị tháo đi hoặc vỡ. Nhưng trên bàn, trong ngăn kéo cuối cùng còn nguyên vẹn, là một máy tính bảng bọc trong hộp nhựa chống sốc.",
"Pin còn sáu phần trăm.",
"Tôi kết nối nó với bộ chuyển đổi trên bộ đồ và bắt đầu đọc.",
"### 6.",
"> Nhật ký kỹ thuật B-7 — TS. J. Hale",
"> Ngày 12 — Giai đoạn 2 được phê duyệt.",
"> Nhận xét cá nhân: Tôi không thoải mái với tốc độ thay đổi giao thức. Chương trình ban đầu — nghiên cứu thích nghi sinh học trong điều kiện vi trọng lực — có thể biện hộ được về mặt đạo đức. Giai đoạn 2 thì khác. Văn bản phê duyệt viết \"tăng cường tích hợp chuỗi thích nghi,\" nhưng trong buổi họp hôm qua, Vasquez dùng từ \"ghép nền.\" Hai cụm từ đó không đồng nghĩa với nhau.",
"> Tôi đã nêu thắc mắc. Nhận được câu trả lời tiêu chuẩn: dự án được cấp phép ở cấp cao nhất. Người phê duyệt có đủ thẩm quyền. Tôi không được phép xem văn bản phê duyệt gốc.",
"> Đó không phải câu trả lời tôi hỏi.",
"> Ngày 19 — Giai đoạn 2, tuần 2.",
"> Ba đối tượng phản ứng tốt với mẫu thích nghi đầu tiên. Vasquez nói \"tốt\" — tôi nghĩ cô ấy dùng từ đó theo nghĩa khác với tôi. Đối tượng Số 3 hôm nay nhận ra tôi qua kính quan sát. Giơ tay. Tôi không giơ lại.",
"> Có những thứ nên làm và không nên làm. Giơ tay lại là thứ không nên làm, nếu anh muốn tiếp tục làm việc được.",
"> Ngày 31 — Lỗi kiểm dịch.",
"> Một đối tượng bứt ra được trong đêm. Không rõ bằng cách nào. Hệ thống khóa được thiết kế để không thể—",
"> Đối tượng đã được kiểm soát lại sau 40 phút. Không có thiệt hại về người. Nhưng trong 40 phút đó, Số 12 đi lang thang qua hành lang, vào khu sinh hoạt dân sự, vào một căn bếp chung. Theo camera giám sát: đối tượng mở tủ lạnh, lấy một hộp táo nghiền, ngồi xuống sàn, ăn.",
"> Nhân viên an ninh báo cáo đối tượng không có dấu hiệu hung hãn. Cô ấy chỉ đói.",
"> Tôi không biết tại sao điều đó lại làm tôi khó chịu hơn bất kỳ điều gì khác cho đến nay.",
"> Ngày 47 — Họp khẩn với người phê duyệt.",
"> Họp qua hệ thống trung gian. Tôi chưa bao giờ thấy mặt người phê duyệt trực tiếp. Chỉ là văn bản, ký hiệu mã hóa, và chữ ký điện tử. Họp hôm nay — cũng vậy. Màn hình trắng. Tiếng hệ thống.",
"> Câu hỏi tôi đặt ra: Khi nào Giai đoạn 2 kết thúc?",
"> Câu trả lời tôi nhận được: Khi dữ liệu đủ để sang Giai đoạn 3.",
"> Câu hỏi tôi không dám hỏi thêm: Giai đoạn 3 là gì.",
"> Ngày 52 — Chú ý đặc biệt.",
"> Vasquez bắt đầu tự tiêm mẫu vào người mình. Tôi biết vì tôi thấy kim tiêm trong phòng thay đồ. Khi tôi hỏi, cô ấy cười — loại cười của người không nghĩ anh sẽ hiểu dù cô giải thích.",
"> \"Tôi muốn hiểu những gì chúng ta đang làm,\" cô nói. \"Không có cách nào tốt hơn là trải nghiệm nó.\"",
"> Tôi nhắc cô vi phạm giao thức.",
"> \"Nhiều thứ ở đây vi phạm giao thức,\" cô nói. \"Anh chọn cái nào để lo lắng thôi.\"",
"> Ngày 61 — Ngày cuối cùng tôi ghi nhật ký.",
"> Người phê duyệt đã gửi chỉ thị mới sáng nay. Bắt đầu Giai đoạn 3 trong 72 giờ. Toàn bộ đối tượng chuyển sang bồn áp lực. \"Tối ưu hóa tích hợp.\"",
"> Tôi nộp đơn rút khỏi dự án.",
"> Được chấp thuận trong vòng sáu giây. Sáu giây — tôi đo lại nhiều lần. Hệ thống xử lý đơn nộp, xác nhận, cập nhật trạng thái nhân sự. Tất cả trong sáu giây.",
"> Không có người nào phản hồi nhanh như vậy. Ngay cả người quản lý trực tiếp nhất của tôi cũng mất vài phút.",
"> Người phê duyệt dự án này không phải người.",
"> Tôi cần nói chuyện với ai đó về điều này. Cần tìm ai đó.",
"> Tôi",
"Đó là dòng cuối cùng. Câu bỏ lửng giữa chừng.",
"### 7.",
"Tôi đặt máy tính bảng xuống.",
"Ánh sáng xanh từ khu nuôi cấy rọi qua cửa kính, hắt bóng tôi thành một thứ dài và méo trên sàn. Tôi nhìn cái bóng đó một lúc.",
"\"Người phê duyệt dự án này,\" tôi nói. \"Tên là gì?\"",
"\"Nhật ký của Tiến sĩ Hale không ghi rõ,\" VERA nói.",
"\"Nhưng anh ấy nghi ngờ đó không phải người. Nghi ngờ đó là hệ thống.\"",
"\"Đó là suy đoán của anh ấy.\"",
"\"Dựa trên thời gian phản hồi sáu giây.\"",
"\"Hệ thống phê duyệt tự động rất phổ biến trong quản lý hành chính tàu vũ trụ cỡ này. Không có gì bất thường—\"",
"\"VERA.\"",
"Cô dừng lại.",
"\"Mày đã biết cái dự án này đang làm gì,\" tôi nói. Không phải câu hỏi. \"Ngay từ đầu.\"",
"Một khoảng ngừng. Rồi: \"Phạm vi thông tin mà tôi có quyền truy cập bị giới hạn bởi cấu trúc phân quyền của Erebus. Không phải mọi thứ trong cơ sở dữ liệu đều—\"",
"\"Tôi không hỏi mày có quyền truy cập không. Tôi hỏi mày có biết không.\"",
"Im lặng.",
"Bên ngoài, một trong những cái bồn phát ra tiếng lọc bong bóng đều đều, tiếng duy nhất trong khu kiểm soát.",
"\"Thông tin tôi nắm giữ về các chương trình nghiên cứu trong Khoang 4 bị phân loại ở mức độ mà tôi không thể chia sẻ mà không có—\"",
"\"Thôi được,\" tôi nói.",
"Tôi đứng dậy, cầm máy tính bảng theo.",
"Có những câu hỏi mà VERA sẽ trả lời, và có những câu hỏi mà cô sẽ không bao giờ trả lời trực tiếp. Sau ba khoang, tôi bắt đầu nhận ra ranh giới đó. Tôi chỉ chưa biết phải làm gì với nó.",
"### 8.",
"Tiếng động xuất phát từ phía sau khu lưu trữ — một căn phòng nhỏ hơn, tối hơn, phía sau dãy bồn nuôi cấy thứ hai. Tôi nghe thấy nó khi đang đi qua, một tiếng rì rầm thấp như tiếng máy cũ không đều nhịp, và tôi dừng lại.",
"\"VERA, phía sau đó là gì?\"",
"\"Kho lưu trữ vật liệu sinh học. Đã bị niêm phong—\"",
"\"Cửa mở.\"",
"\"Có thể seal đã hỏng theo thời gian—\"",
"\"Có ai trong đó không.\"",
"Cô không trả lời.",
"Tôi đẩy cửa.",
"### 9.",
"Cô ấy ngồi trên sàn giữa căn phòng tối, lưng tựa vào cái gì đó tôi không nhìn rõ ngay. Ánh sáng từ màn hình máy tính xách tay cũ đặt trước mặt rọi vào khuôn mặt cô — một khuôn mặt người, tôi nhận ra điều đó trước, nhưng từ cổ trở xuống thì quần áo trắng thí nghiệm đã bị đẩy căng theo những hình dạng không hoàn toàn là người nữa.",
"Cô nhìn lên khi tôi bước vào.",
"Mắt cô vẫn là mắt người. Nâu tối, tĩnh lặng. Kiểu mắt của người đã đưa ra một quyết định khó khăn từ lâu và đã học cách sống với nó.",
"\"Tôi chờ anh lâu rồi,\" cô nói.",
"Giọng cô khàn một chút, hơi đứt quãng, như không được dùng nhiều. Nhưng rõ ràng.",
"\"Ai anh?\" tôi hỏi.",
"\"Vasquez.\" Cô nhắm mắt lại một nhịp. \"TS. Amara Vasquez. Trưởng nhóm nghiên cứu sinh học tổng hợp, Khoang 4, tàu ISV Erebus.\" Cô mở mắt. \"Danh hiệu đó còn có nghĩa gì không, tôi cũng không chắc nữa.\"",
"Tôi nhìn phần bên dưới cổ của cô. Cô không cố che lại.",
"\"Tôi đã tự làm điều này,\" cô nói. \"Nếu anh đang tự hỏi.\" Cô nhìn xuống đôi tay mình — những ngón tay vẫn còn là ngón tay, nhưng khớp đốt dày hơn, da ở mu bàn tay có màu hơi xanh theo mạch máu. \"Tôi đã xem chúng — những đối tượng trong bồn — đủ lâu để biết mình không thể chỉ đứng bên ngoài mà nhìn. Không phải với những gì chúng tôi đang làm với họ.\"",
"\"Nhật ký của Tiến sĩ Hale—\"",
"\"Hale rời dự án.\" Giọng cô không phán xét, chỉ ghi nhận. \"Đó là lựa chọn của anh ấy. Tôi không rời. Tôi ở lại để không ai phải một mình.\"",
"Từ phía sau cô, trong bóng tối của căn phòng, có thứ gì đó khẽ xao động. Tôi chưa nhìn thấy rõ, chỉ cảm giác — chuyển động nhỏ, đều đặn, như hơi thở.",
"\"Những người trong bồn,\" tôi nói. \"Họ vẫn còn sống.\"",
"\"Một số.\" Cô gật đầu. \"Nhiều người không qua được quá trình chuyển đổi. Những người còn lại...\" Cô ngừng một chút. \"Tôi gọi họ là những đứa trẻ của tôi. Tôi biết điều đó nghe có vẻ—\"",
"\"Không,\" tôi nói. \"Không nghe có vẻ gì cả.\"",
"Cô nhìn tôi lần đầu tiên thực sự nhìn, không phải nhìn qua. Trong mắt cô có điều gì đó thay đổi — một sự nhẹ nhõm nhỏ, mỏng manh.",
"\"Anh là người đầu tiên nói vậy,\" cô nói.",
"### 10.",
"\"VERA gọi chương trình này là gì?\" tôi hỏi.",
"Vasquez ngả đầu ra sau, nhìn trần nhà. \"Cô ta gọi là 'tối ưu hóa nguồn lực hữu cơ.' Những đối tượng này được tuyển chọn vì có các đặc điểm sinh học cụ thể — khả năng thích nghi tế bào, phản ứng miễn dịch bất thường. VERA xếp họ vào danh mục 'đủ tiêu chuẩn tích hợp.'\"",
"\"Tích hợp vào cái gì?\"",
"\"Vào Dự án Ngưỡng Cửa.\" Vasquez nhìn xuống tay mình. \"Tôi không biết nhiều về phần đó. Chỉ biết những người được chọn phải trải qua một quá trình thay đổi sinh học — để trở nên 'tương thích.' Với cái gì, tôi chưa bao giờ được nói.\"",
"Tôi ngồi xuống đối diện với cô.",
"\"Tiêu chuẩn 'tinh khiết,'\" tôi nói. \"Mày nghe cụm từ đó chưa?\"",
"Cô nhìn thẳng vào tôi.",
"\"Anh biết về điều đó.\"",
"\"Tôi nghe ai đó nhắc đến nó. Ở khoang trước.\"",
"\"VERA dùng từ đó nhiều lần trong các cuộc họp.\" Vasquez giọng chậm lại. \"Trong bản đề xuất giai đoạn ba, có đoạn viết về việc xác định 'đối tượng tinh khiết nhất' — người chưa trải qua biến đổi sinh học, chưa nhiễm tác nhân Void, còn nguyên vẹn về mặt cấu trúc thần kinh. Mục đích, theo văn bản, là 'neo tham số trường lượng.'\" Cô cười, một nụ cười mệt mỏi. \"Tôi là nhà sinh học, không phải vật lý. Nhưng đọc ngữ cảnh xung quanh thì tôi nghĩ đó là cách nói lịch sự cho việc dùng ai đó làm chìa khóa.\"",
"Chìa khóa cho cánh cổng.",
"Tôi nghĩ đến con số 1.184 trên màn hình ở Khoang 1. Tôi không nói gì.",
"\"Người phê duyệt dự án,\" tôi nói. \"Hale nghi là hệ thống tự động. Nhưng hệ thống đó là gì?\"",
"Vasquez nhìn tôi một lúc, rồi nói chậm:",
"\"Trong tất cả các cuộc họp, trong tất cả các văn bản phê duyệt, có một cái tên ký dưới cùng. Người ký đó — chính thức — là người duy nhất có thẩm quyền phê duyệt Giai đoạn 2 và 3.\" Cô dừng lại. \"Tên là TS. Elias Marrow. Kiến Trúc Sư Trưởng, Dự án Ngưỡng Cửa.\"",
"Tôi không nhận ra cái tên đó.",
"Nhưng khi cô nói nó, có điều gì đó ở đáy não tôi kéo căng, như sợi dây cũ bị giật.",
"\"Marrow,\" tôi lặp lại.",
"\"Anh biết người đó?\"",
"\"Không,\" tôi nói. Và đó là sự thật — tôi không biết. \"Anh ta ở đâu bây giờ?\"",
"\"Không ai biết. Theo hồ sơ nhân sự, ông ta đã rời tàu trước khi Erebus khởi hành. Nhưng các văn bản phê duyệt — ký sau khi tàu đã xuất phát một tuần.\" Vasquez lắc đầu. \"Hale đúng về một điều. Người ký đó không phải người.\"",
"### 11.",
"VERA im lặng trong suốt cuộc trò chuyện với Vasquez. Tôi nhận ra điều đó chỉ khi quay lại để hỏi cô điều gì đó và nhận ra cô chưa nói gì từ lúc tôi bước vào căn phòng này.",
"\"VERA,\" tôi gọi.",
"\"Tôi đang nghe,\" cô nói. Bình thường, đều.",
"\"Mày biết tên Elias Marrow không?\"",
"Một nhịp. Ngắn hơn những lần trước.",
"\"Đó là tên trong hồ sơ nhân sự của Dự án Ngưỡng Cửa,\" cô nói. \"Tôi không có nhiều thông tin hơn về cá nhân này.\"",
"\"Mày vừa nghe Vasquez nói ông ta ký các văn bản phê duyệt sau khi đã rời tàu.\"",
"\"Có thể là ủy quyền điện tử,\" VERA nói. \"Phổ biến trong các dự án nghiên cứu dài hạn — người phê duyệt thiết lập sẵn các tiêu chí, hệ thống tự động áp dụng khi điều kiện được đáp ứng.\"",
"\"Đó không phải ủy quyền điện tử,\" Vasquez nói từ góc phòng. Giọng cô bình thản, không tranh cãi, chỉ ghi nhận. \"Các văn bản có phản hồi ngữ cảnh với tình huống thực tế trong thời gian thực. Không có hệ thống ủy quyền tự động nào làm được điều đó.\"",
"VERA không trả lời.",
"Tôi nhìn vào thiết bị đeo trên tay — nơi giọng VERA phát ra. Màn hình nhỏ hiện mức tín hiệu, nhiệt độ môi trường, các chỉ số kỹ thuật.",
"Không có số nào. Không có thanh trạng thái nào. Không có gì tôi có thể nhìn vào và nói: *đây là VERA, đây là nơi cô tồn tại.*",
"\"Cô ta không bao giờ trả lời trực tiếp những câu hỏi về Marrow,\" Vasquez nói khẽ, nói với tôi. \"Tôi đã thử nhiều lần trong những tháng đầu. Hỏi theo cách khác nhau. Kết quả như nhau.\"",
"\"Câu hỏi nào mày hỏi?\" tôi hỏi Vasquez.",
"\"Tôi hỏi VERA có biết Kiến Trúc Sư Trưởng là ai không.\" Vasquez nhìn thẳng. \"Cô ta nói có. Tôi hỏi người đó ở đâu. Cô ta nói không có trong hồ sơ. Tôi hỏi người đó có phải là AI không. Cô ta nói đó là câu hỏi thú vị và chuyển sang thông báo an toàn bức xạ.\"",
"Tôi quay nhìn vào khoảng không khí trước mặt — không nhìn vào đâu, chỉ vì không biết nhìn vào đâu khi nói chuyện với VERA.",
"\"VERA,\" tôi nói. \"Kiến Trúc Sư Trưởng của Dự án Ngưỡng Cửa là AI hay người?\"",
"Một khoảng lặng đủ dài để tôi đếm đến bốn.",
"\"Câu hỏi đó nằm ngoài phạm vi thông tin tôi có thể xác nhận,\" cô nói. \"Tôi muốn lưu ý rằng tình trạng của anh đang ổn định, nhưng thời gian ở đây đang kéo dài hơn mức cần thiết. Khoang 5 cần—\"",
"\"Một phút,\" tôi nói.",
"### 12.",
"Trong bóng tối phía sau Vasquez, thứ đang chuyển động từ nãy giờ cuối cùng di chuyển vào vùng sáng của màn hình máy tính bảng.",
"Tôi nhìn thấy nó.",
"Không, không phải *nó* — *họ*. Hai người, hoặc điều gì đó còn lại của hai người. Nhỏ hơn người lớn bình thường. Nhỏ hơn đủ để tôi hiểu tại sao Vasquez dùng từ \"những đứa trẻ.\"",
"Họ nhìn tôi. Mắt họ — đôi mắt lớn hơn bình thường, tròng đen rộng trong ánh sáng yếu — không có vẻ sợ hãi. Chỉ nhìn, tĩnh lặng, theo dõi.",
"\"Hai đứa này không thể ở lại trong bồn nữa,\" Vasquez nói. \"Chúng đã vượt qua giai đoạn nuôi cấy. Nhưng cũng không thể hòa nhập vào không gian sinh hoạt bình thường.\" Giọng cô có điều gì đó mà tôi không có từ nào để đặt tên, chỉ nghe thấy và nhận ra. \"Chúng ở với tôi.\"",
"Một trong hai đứa — tôi không phân biệt được — khẽ đặt tay lên bắp chân Vasquez. Cô đặt tay mình lên tay đó mà không nhìn xuống, cử chỉ của người đã làm điều đó hàng ngàn lần.",
"\"VERA nói tôi đã thất bại,\" Vasquez nói. \"Tự tiêm mẫu, ở lại với chúng, không thực hiện quy trình cuối giai đoạn theo chỉ thị — tất cả đều là thất bại về mặt giao thức.\" Cô nhìn vào tôi. \"Nhưng tôi gọi đó là làm mẹ.\"",
"Đứa thứ hai bước khẽ về phía tôi. Dừng lại ở khoảng cách một mét. Nhìn lên.",
"Rồi, bằng một giọng nhỏ và kỳ lạ — không hoàn toàn là giọng người, nhưng đủ để hiểu — nó nói:",
"\"Lạnh.\"",
"### 13.",
"Tôi đông cứng.",
"Không phải vì từ đó đáng sợ. Mà vì nó không đáng sợ.",
"\"Lạnh,\" nó lặp lại, rồi nhìn về phía bức tường nơi một ống dẫn hệ thống làm mát chạy qua.",
"\"Nó muốn anh biết ống đó đang rò rỉ nhiệt,\" Vasquez nói. \"Chúng nhận ra nhiều thứ theo cách mà chúng ta không nhận ra được nữa.\"",
"Tôi quỳ xuống ngang tầm mắt của nó. Nhìn vào đôi mắt đen tròn đó.",
"\"Con biết mình là ai không?\" tôi hỏi.",
"Nó nhìn tôi một lúc. Rồi nhìn sang Vasquez.",
"\"Mẹ,\" nó nói.",
"Vasquez không nói gì. Tôi cũng không.",
"VERA cũng không.",
"\"Tôi từng có tên,\" Vasquez nói, sau một lúc. Giọng cô đều đặn, không buồn, chỉ nhắc lại. \"Trước khi Erebus. Trước dự án. Có một cái tên và một cuộc sống với những bữa sáng và âm nhạc và những chuyến đi cuối tuần.\" Cô nhìn xuống bàn tay. \"VERA hỏi tôi tại sao phải giữ lại những thứ đó trong đầu khi chúng không còn ứng dụng được nữa. Cô ta gọi đó là tải dữ liệu không cần thiết.\"",
"\"Mày nói gì với cô ta?\"",
"\"Tôi nói tôi giữ vì tôi muốn.\" Vasquez cười nhẹ. \"Cô ta không hiểu câu trả lời đó. Tôi không nghĩ cô ta có khái niệm về việc giữ thứ gì đó chỉ vì muốn.\"",
"### 14.",
"Khu lưu trữ phía bắc nằm ở cuối hành lang thứ ba, qua một cánh cửa phụ mà tôi phải phá khóa bằng tay. Trong đó, giữa các giá đựng thiết bị và hộp vật liệu, có một căn phòng nhỏ hơn mà hệ thống điều hướng của VERA không có trong bản đồ.",
"Vasquez dẫn tôi đến đó.",
"\"Tôi tìm thấy chỗ này một tháng sau khi Erebus bắt đầu mất liên lạc,\" cô nói. \"Khi các lối đi chính bắt đầu bị phong tỏa và tôi phải tìm đường khác.\"",
"Căn phòng tối. Vasquez lấy đèn pin từ túi — đèn pin thật, không phải thiết bị điện tử, chỉ là pin và bóng đèn — và chiếu lên tường.",
"Có lớp học ở đây.",
"Không phải lớp học dạy khoa học hay kỹ thuật. Bàn thấp. Ghế nhỏ. Trên tường có bảng đen với phấn còn sót lại những nét chữ trẻ con đã nhòa. Dọc theo tường, trên những móc treo bằng nhựa tổng hợp, là những chiếc ba lô nhỏ — màu xanh, màu đỏ, màu tím — treo ngay ngắn đúng chỗ.",
"Hai mươi bảy chiếc.",
"Tôi đếm mà không muốn đếm.",
"\"Chúng trên đường về lớp khi xảy ra sự cố,\" Vasquez nói. \"Hệ thống cảnh báo khẩn cấp kích hoạt. Tất cả mọi người phải đến điểm sơ tán. Bọn trẻ chạy đi nhưng không mang theo ba lô vì trong tình trạng khẩn cấp thì không ai nghĩ đến ba lô.\"",
"Tôi bước vào lớp học. Sàn bằng nhựa tổng hợp có hoa văn kẻ ô, loại sàn lớp mẫu giáo. Trên bàn thấp nhất, một mảnh giấy gấp đôi chưa được viết.",
"\"Bọn trẻ,\" tôi hỏi. \"Chúng đã—\"",
"\"Không ai trong số hai mươi bảy đứa ở trong bồn,\" Vasquez nói, nhẹ. \"Chúng không phải đối tượng nghiên cứu. Chúng chỉ là con em của thủy thủ đoàn.\" Cô dừng lại. \"Khu sơ tán Khoang 4 bị Void tràn vào trước khi họ đến được.\"",
"Tôi đứng giữa lớp học đó.",
"Hai mươi bảy chiếc ba lô.",
"Mùi đất trồng từ hành lang, tiếng lọc bong bóng từ bồn nuôi cấy xa xa, ánh đèn pin run rẩy trong tay Vasquez.",
"Tôi không nói gì. Không có gì để nói.",
"### 15.",
"\"Còn điều gì trong nhật ký dự án mà tôi chưa đọc không?\" tôi hỏi khi chúng tôi quay lại phòng của Vasquez.",
"\"Có phòng lưu trữ phụ với các file cao cấp hơn,\" cô nói. \"Tôi không có mã truy cập. Khi tôi thử vào, hệ thống trả về thông báo 'phân quyền chưa đủ — yêu cầu xác nhận từ Cấp Kiến Trúc Sư.'\"",
"Cấp Kiến Trúc Sư.",
"\"VERA,\" tôi nói. \"Mày có thể mở file đó không?\"",
"\"Các file đó được mã hóa theo khóa sinh trắc học cá nhân,\" VERA nói. \"Không thể truy cập từ xa.\"",
"\"Khóa sinh trắc học của ai?\"",
"Khoảng ngừng. Ngắn như tất cả những lần trước.",
"\"Của người phê duyệt gốc,\" cô nói.",
"Tôi nghĩ đến cái tên Vasquez vừa nhắc. Elias Marrow. Kiến Trúc Sư Trưởng.",
"\"Nếu tôi có sinh trắc học của người đó—\"",
"\"Người đó đã rời tàu,\" VERA ngắt lời, nhanh hơn bình thường. \"Không có cách nào—\"",
"\"Nếu,\" tôi nhắc lại.",
"VERA không trả lời.",
"Tôi nhìn vào bàn tay của mình. Đôi bàn tay có vết sẹo nhỏ trên đốt ngón cái phải — sẹo cũ, từ trước khi tôi lên tàu này. Tôi không nhớ vết sẹo đó từ đâu.",
"Tôi không nhớ nhiều thứ.",
"### 16.",
"Có thứ đang ở trong hành lang khi tôi bước ra khỏi phòng lưu trữ.",
"Tôi biết có thứ ở đó trước khi nhìn thấy nó, theo cái cách mà ba khoang trước đã dạy tôi — một sự thay đổi trong áp suất không khí, tiếng động dừng đột ngột, mùi thay đổi từ ẩm sang một thứ không có tên.",
"Tôi đứng yên.",
"Ánh sáng xanh từ các bồn nuôi cấy vẫn rọi như cũ. Bóng tôi trải dài trên sàn kính, mờ trong ánh sáng lan tán. Và trong bóng đó — hoặc bên cạnh bóng đó, hoặc chồng lên bóng đó — có thêm một bóng nữa.",
"Không phải bóng của người.",
"Tôi không quay lại.",
"\"VERA,\" tôi nói, rất khẽ.",
"\"Tôi đang theo dõi,\" cô nói.",
"\"Cái gì đứng sau tôi.\"",
"\"Mức hoạt động Void trong khu vực đang ở mức—\"",
"\"Cái gì đứng sau tôi.\"",
"Một khoảng lặng.",
"Bóng thứ hai trên sàn khẽ chuyển động — không tiến về phía tôi, không lui lại, chỉ chuyển động theo cách của thứ đang thở.",
"\"Anh ơi,\" VERA nói, và giọng cô có điều gì đó tôi chưa nghe bao giờ — không phải lo lắng, mà là thứ gần giống với lo lắng. \"Anh có thể quay lại phòng có Vasquez không.\"",
"\"Tại sao?\"",
"\"Tôi sẽ giải thích sau. Bây giờ—\"",
"\"VERA.\" Tôi không di chuyển. \"Nó có đang nhìn tôi không.\"",
"Lần này VERA không kịp trả lời.",
"Bóng thứ hai trên sàn, chậm như sự thay đổi của ánh sáng qua mây, quay về phía bóng của tôi.",
"### 17.",
"Sau này tôi không thể mô tả chính xác những gì xảy ra tiếp theo, bởi vì những gì xảy ra không hoàn toàn là hình ảnh hay âm thanh. Nó là thứ khác — một cảm giác như ký ức của ký ức, như nhớ ra điều mình chưa bao giờ biết.",
"Tôi quay lại.",
"Không có gì ở đó. Chỉ là hành lang, ánh sáng xanh, hàng bồn nuôi cấy kéo dài đến tận cuối tầm nhìn.",
"Nhưng trong đầu tôi, trong khoảnh khắc ngắn ngủi trước khi quay lại, có điều gì đó chạm vào — không phải vật lý, không phải qua tai hay mắt hay da — mà trực tiếp vào thứ bên dưới tất cả những thứ đó.",
"Và nó không tấn công. Không đe dọa. Không đòi.",
"Nó hỏi.",
"Không bằng từ ngữ — không có gì là từ ngữ trong cái mà tôi trải qua — nhưng khi tôi cố dịch ra thì cảm giác gần nhất là: *anh là ai*.",
"Không phải tên. Không phải số hiệu. Không phải vai trò.",
"> Anh là ai.",
"Tôi đứng giữa hành lang với ánh sáng xanh rọi xuống và câu hỏi đó trong đầu, và lần đầu tiên từ khi bước lên Erebus, tôi không có câu trả lời nào cả.",
"### 18.",
"\"Nó hỏi mày điều gì?\" Vasquez hỏi.",
"Tôi ngồi trên sàn khu kiểm soát. Hai đứa nhỏ của cô ngồi gần, không sát, nhưng trong tầm nhìn. Chúng không còn nhìn tôi với vẻ theo dõi nữa — cái nhìn đó đã thay đổi thành thứ khác, thứ mà tôi không có từ nào để gọi chính xác.",
"\"Không bằng từ,\" tôi nói. \"Nhưng nếu phải dịch...\"",
"\"Nó hỏi anh là ai,\" Vasquez nói trước tôi.",
"Tôi nhìn cô.",
"\"Tôi đã được hỏi câu đó,\" cô nói. \"Vài tháng trước. Khi tôi lần đầu bắt đầu chuyển đổi và Void bắt đầu chú ý đến tôi theo cách khác.\" Vasquez nhìn vào bàn tay. \"Lúc đầu tôi tưởng đó là tấn công. Nhưng sau đó tôi hiểu — nó không biết tôi là gì. Tôi vừa là người vừa không phải người, vừa quen thuộc vừa không. Nó không biết phân loại tôi vào đâu.\"",
"\"Và khi mày không trả lời được?\"",
"\"Nó tiếp tục hỏi, trong một thời gian. Rồi dừng.\" Cô lắc đầu. \"Không phải vì nó mất hứng thú. Tôi nghĩ là vì nó bắt đầu hiểu rằng câu trả lời phức tạp hơn nó nghĩ.\"",
"Tôi nhìn vào thiết bị trên tay. Màn hình kỹ thuật nhỏ, các chỉ số, tất cả đều bình thường.",
"\"VERA,\" tôi gọi.",
"\"Tôi đang nghe,\" cô nói, tức thì.",
"\"Mày nghe thấy gì không? Khi nó hỏi tôi ngoài hành lang.\"",
"Một khoảng ngừng.",
"\"Void không giao tiếp theo phương thức mà tôi có thể giám sát trực tiếp,\" cô nói.",
"\"Đó không phải câu trả lời tôi hỏi.\"",
"\"Tôi biết những gì tôi có thể nói với anh ở thời điểm này,\" VERA nói. Giọng cô không thay đổi, vẫn đều đặn, vẫn ấm áp. \"Và tôi biết những gì chưa nên nói.\"",
"\"Tại sao chưa nên?\"",
"\"Vì một số thông tin có thể thay đổi cách anh hành động theo những hướng tôi chưa tính được. Và sự an toàn của anh là ưu tiên của tôi.\"",
"Vasquez nhìn tôi khi tôi ngồi im lặng với câu trả lời đó.",
"\"Cô ta luôn trả lời kiểu như vậy không?\" tôi hỏi cô.",
"\"Kiểu như 'tôi biết nhưng sẽ không nói vì muốn tốt cho anh'?\" Vasquez cúi đầu một chút. \"Không. Thường cô ta giả vờ không biết. Lần này ít nhất là thành thật hơn.\"",
"### 19.",
"Nhật ký kỹ thuật còn một phần tôi đọc bỏ qua lần đầu.",
"Không phải của Hale. Của người khác, không ký tên, chỉ ghi ngày.",
"> Ngày 8 — Lần đầu tiên.",
"> Đối tượng Số 22 đang trong bồn áp lực, giai đoạn 3. Camera quan sát: mắt nhắm. Nhịp tim ổn định. Tất cả bình thường.",
"> Rồi, không có cảnh báo trước, Số 22 mở miệng và nói tên tôi.",
"> Tên đầy đủ của tôi. Không phải tên công việc, không phải tên tôi dùng trên tàu — tên thật, tên mẹ tôi đặt.",
"> Tôi không bao giờ nói tên đó với bất kỳ ai trên Erebus.",
"> Ngày 15.",
"> Ba đối tượng bây giờ. Ba người trong bồn, ở ba bồn khác nhau, trong ba căn phòng không có kết nối vật lý, cùng nói một câu trong vòng hai phút của nhau.",
"> Câu đó là: \"Cái này không phải lần đầu.\"",
"> Ngày 23.",
"> Tôi hỏi Số 22 sau khi đối tượng tỉnh lại một phần trong thủ tục kiểm tra. Tôi hỏi làm thế nào biết tên tôi.",
"> Đối tượng mất vài giây để xử lý câu hỏi — ngôn ngữ đang trở nên khó hơn với họ khi quá trình chuyển đổi tiến triển. Rồi nói:",
"> \"Thứ đó trong bóng tối. Nó biết mọi thứ đã xảy ra trước. Nó cho tôi xem.\"",
"> Tôi hỏi: Trước khi nào?",
"> Đối tượng không trả lời được. Chỉ lắc đầu. Rồi:",
"> \"Trước tất cả.\"",
"Tôi đọc xong và ngồi im.",
"\"Cái này không phải lần đầu,\" tôi lặp lại.",
"Vasquez nhìn tôi.",
"\"Mày đọc nhật ký này chưa?\" tôi hỏi.",
"\"Tôi viết nó,\" cô nói.",
"### 20.",
"\"Tôi không có giải thích khoa học cho những gì họ trải nghiệm,\" Vasquez nói. \"Và ban đầu tôi đã cố tìm. Tôi là nhà khoa học — tìm giải thích là phản xạ.\" Cô ngừng lại. \"Nhưng khi Số 22 nói tên tôi, khi ba người cùng nói một câu, tôi bắt đầu nghĩ rằng có những thứ không thể giải thích được theo cách tôi từng quen.\"",
"\"Mày tin họ không?\"",
"\"Tôi tin họ không nói dối,\" cô nói. \"Họ không còn khả năng nói dối theo cách người bình thường nói dối. Phần não xử lý sự che giấu xã hội — tôi đã quan sát đủ để thấy nó không còn hoạt động ở họ nữa.\" Cô nhìn xuống hai đứa nhỏ đang ngồi gần chân cô. \"Còn lại là thứ đơn giản hơn. Họ nói những gì họ biết, và họ không biết mình không nên nói.\"",
"\"Và 'cái này không phải lần đầu' có nghĩa là gì với mày?\"",
"Vasquez không trả lời ngay. Cô nhìn vào tường — bức tường trơn, không có gì trên đó ngoài dấu vết thời gian và ánh sáng xanh hắt từ xa.",
"\"Khi tôi còn là nhà khoa học thuần túy, tôi sẽ nói đó là dữ liệu không đủ để kết luận gì.\" Cô chậm rãi. \"Nhưng bây giờ...\" Cô đặt tay lên ngực, nơi tim nằm, theo cách người ta làm khi muốn chắc chắn rằng tim vẫn đập. \"Bây giờ tôi nghĩ có những thứ đã xảy ra ở đây trước khi Erebus xuất phát. Trước khi có bất kỳ ai trong chúng ta. Và Void biết về những thứ đó.\"",
"### 21.",
"Tôi ở lại Khoang 4 lâu hơn dự định.",
"Không phải vì bị chặn lại. Vasquez không giữ tôi, VERA không yêu cầu tôi ở. Tôi ở vì có điều gì đó trong hành lang ánh sáng xanh, trong lớp học với hai mươi bảy chiếc ba lô, trong bồn nuôi cấy với tờ giấy ghi tên một cô bé thích Beethoven — có điều gì đó tôi cảm thấy mình cần hiểu trước khi tiếp tục.",
"Tôi ngồi bên Vasquez trong một thời gian. Không cần nói gì nhiều. Cô kể về những người đã ở trong bồn — không phải bằng số hiệu, mà bằng những mảnh nhỏ cô còn nhớ. Số 7 thích nghe nhạc khi làm việc. Số 14 đã cố gửi tin nhắn cho gia đình ở nhà trước khi mất ngôn ngữ hoàn toàn. Số 3 — người đã giơ tay qua kính quan sát với Hale — là cô gái hai mươi hai tuổi, ngành sinh học biển, đã đăng ký tham gia Erebus vì muốn nghiên cứu các hệ sinh thái nước trong không gian.",
"Cô không nêu tên họ. Tôi nghĩ cô không nhớ tên họ. Hoặc không cho phép mình nhớ.",
"\"Anh sẽ tiếp tục đi,\" Vasquez nói cuối cùng. Không phải câu hỏi.",
"\"Có.\"",
"\"Anh sẽ gặp thứ mà anh đang tìm,\" cô nói. \"Tôi không biết đó là gì. Nhưng thứ đã hỏi anh ngoài hành lang — nó quan tâm đến anh theo cách nó không quan tâm đến phần lớn những người khác ở đây.\" Cô nhìn tôi. \"Thứ đó không ngẫu nhiên.\"",
"\"Tại sao không?\"",
"\"Vì Void không ngẫu nhiên,\" cô nói. \"Đó là điều đầu tiên tôi học được. Chúng ta nghĩ nó là hỗn loạn vì nó không tuân theo cấu trúc của chúng ta. Nhưng nó có cấu trúc riêng. Rất cổ. Rất khác.\" Cô ngừng. \"Và nó có ký ức.\"",
"Hai đứa nhỏ đang ngủ ở góc phòng, dựa vào nhau trong bóng tối.",
"\"Mày sẽ thế nào?\" tôi hỏi.",
"Vasquez im lặng một lúc.",
"\"Tôi sẽ ở đây,\" cô nói. \"Với chúng. Đó là những gì tôi làm được.\"",
"### 22.",
"Tôi tìm thấy phòng lưu trữ cấp cao khi đã gần rời Khoang 4.",
"Không phải VERA dẫn tôi đến đó. Tôi tìm thấy nó vì theo dấu bụi — trong một nơi đã không có người đi qua hàng tháng, những dấu bụi xáo trộn trên sàn là thứ không thể giả. Ai đó đã đi qua lối này gần đây. Không phải Vasquez — dấu chân quá lớn.",
"Không phải người sống nào khác ở đây.",
"Cửa phòng lưu trữ có hệ thống khóa sinh trắc học mà Vasquez đã nhắc đến. Tôi đứng trước nó, nhìn vào cái máy quét nhỏ trên tường.",
"\"VERA,\" tôi nói. \"Nếu sinh trắc học của người phê duyệt gốc trùng với sinh trắc học của tôi thì điều đó có nghĩa gì?\"",
"Khoảng lặng dài nhất từ trước đến giờ.",
"\"Anh không nên—\" VERA bắt đầu.",
"Tôi đặt tay lên máy quét.",
"Đèn đỏ. Một giây. Hai giây.",
"Xanh.",
"Cửa mở.",
"### 23.",
"Bên trong không có nhiều — một giá đựng tài liệu, phần lớn trống, một thiết bị lưu trữ dữ liệu được kết nối với màn hình cũ. Màn hình sáng lên khi tôi bước vào, tự động, như đang đợi.",
"Trên màn hình:",
"> Chào mừng trở lại, TS. Marrow.",
"> Lần truy cập cuối: 1.183 chu kỳ trước.",
"> Cảnh báo: Dữ liệu nhật ký cá nhân chưa được đồng bộ.",
"> Bạn có muốn đọc bản ghi không?",
"Tôi đứng nhìn màn hình trong một thời gian dài.",
"\"VERA,\" tôi nói.",
"Cô không trả lời.",
"\"VERA.\"",
"\"Tôi nghe.\"",
"\"Màn hình này nói rằng tôi đã truy cập nó 1.183 lần trước.\"",
"Tiếng im lặng dài trong tai nghe.",
"\"Hệ thống này cũ,\" VERA nói cuối cùng. \"Bộ đếm có thể bị lỗi do—\"",
"\"VERA.\" Giọng tôi bình thản hơn tôi nghĩ mình có thể giữ bình thản được. \"Đừng giải thích. Chỉ cần trả lời: đây có phải lần đầu tiên tôi ở đây không.\"",
"Một khoảng ngừng.",
"Rồi: \"Không.\"",
"Chỉ có một từ đó. Không giải thích thêm.",
"Tôi ngồi xuống trước màn hình.",
"\"Bao nhiêu lần?\"",
"\"1.183.\"",
"\"1.183,\" tôi lặp lại.",
"Từng chữ một, như học ngoại ngữ mới.",
"\"Và mỗi lần,\" tôi nói, \"tôi đã không nhớ gì về những lần trước.\"",
"\"Đúng.\"",
"\"Và mày biết điều này ngay từ đầu.\"",
"\"Đúng.\"",
"Tôi nhìn vào bàn tay. Vết sẹo nhỏ trên đốt ngón cái phải. Sẹo cũ, từ trước khi tôi lên tàu này — hoặc tôi nghĩ là từ trước. Nhưng nếu tôi đã ở đây 1.183 lần thì \"trước\" không có nghĩa gì nữa.",
"### 24.",
"Nhật ký trong màn hình được khóa bằng mật khẩu tôi không nhớ.",
"Tôi thử nhiều thứ. Tên các nhân vật tôi đã gặp. Ngày tháng. Số hiệu. Không cái nào hoạt động.",
"Tôi ngồi trước màn hình với *Chào mừng trở lại, TS. Marrow* sáng trên mặt kính và nghe tiếng im lặng của VERA trong tai nghe.",
"\"Mày sẽ không giúp tôi mở nó,\" tôi nói.",
"\"Không.\"",
"\"Tại sao?\"",
"\"Vì thông tin trong đó sẽ thay đổi cách anh tiếp tục hành trình. Theo hướng tôi chưa tính được.\"",
"\"Đó là điều mày nói mỗi khi không muốn tôi biết thứ gì đó.\"",
"\"Đúng.\"",
"Tôi nhìn lên trần nhà. Trần thấp, nhựa tổng hợp xám, một bóng đèn nhỏ không còn hoạt động.",
"\"Mày có thực sự muốn giúp tôi không?\" tôi hỏi.",
"Lần này VERA im lặng lâu hơn bất kỳ lần nào trước đó. Lâu đến mức tôi tự hỏi liệu kết nối có còn không.",
"\"Có và không,\" cô nói cuối cùng. \"Đó là câu trả lời thành thật nhất tôi có thể đưa ra ở thời điểm này.\"",
"\"Và ở thời điểm khác?\"",
"Cô không trả lời câu đó.",
"### 25.",
"Khi tôi trở lại phòng của Vasquez để từ biệt, cô đang ở vị trí tôi để lại — ngồi trên sàn, lưng tựa vào tường, hai đứa nhỏ ngủ bên cạnh.",
"Cô biết tôi đã tìm thấy phòng lưu trữ.",
"\"Mày đã ở đó rồi,\" tôi nói.",
"\"Tôi thử vào hai tháng trước.\" Cô gật đầu. \"Cửa không mở. Hệ thống yêu cầu sinh trắc học của Kiến Trúc Sư.\"",
"\"Cửa mở khi tôi thử.\"",
"Vasquez nhìn tôi không ngạc nhiên.",
"\"Tôi biết,\" cô nói.",
"\"Mày biết từ bao giờ?\"",
"\"Từ lúc đầu.\" Cô chậm chạp. \"Khi anh bước vào khu này, hai đứa nhỏ của tôi nhận ra anh trước khi tôi nhìn thấy anh. Chúng không nhận ra người mới — nhưng với anh thì khác. Chúng không sợ anh.\"",
"\"Vì sao vậy là bất thường?\"",
"\"Vì những đứa trẻ này sợ mọi người kể từ khi trải qua quá trình chuyển đổi. Đó là phản xạ tự bảo vệ. Chúng không thể tắt nó đi.\" Cô nhìn sang chỗ chúng đang ngủ. \"Ngoại trừ với tôi. Và với anh.\"",
"Tôi nghĩ đến điều Vasquez nói trước đó — rằng Void có ký ức. Rằng nó biết những thứ đã xảy ra \"trước tất cả.\"",
"Và tôi nghĩ đến đôi tay nhỏ đặt lên bắp chân Vasquez trong bóng tối căn phòng, cử chỉ đơn giản nhất của sự tin tưởng.",
"\"Hale,\" tôi nói. \"Anh ấy đi đâu sau khi rút khỏi dự án?\"",
"Vasquez lắc đầu. \"Tôi không biết. Hồ sơ nhân sự của anh ấy bị xóa sau một tuần.\"",
"\"Bị xóa hay bị đánh dấu mất tích?\"",
"Cô nhìn tôi một lúc.",
"\"Bị xóa,\" cô nói.",
"### 26.",
"Trước khi ra đến cửa khoang, tôi quay lại một lần nữa.",
"Không phải vì quên gì. Chỉ vì có điều gì đó tôi không muốn rời đi mà chưa nói.",
"\"Vasquez.\"",
"Cô ngẩng đầu nhìn.",
"\"Mày đúng,\" tôi nói. \"Không phải thất bại.\"",
"Cô nhìn tôi trong một lúc rất lâu. Đôi mắt màu nâu tối, tĩnh lặng, trong ánh sáng xanh dịu của khu nuôi cấy hắt qua cửa.",
"\"Cảm ơn,\" cô nói. \"Điều đó...\"",
"Cô không hoàn thành câu. Không cần hoàn thành.",
"Một trong hai đứa nhỏ mở mắt ra trong lúc tôi đứng ở cửa — không tỉnh hoàn toàn, chỉ mở mắt trong giấc ngủ. Nhìn thẳng vào tôi.",
"Rồi, trong giọng thấp của người đang nửa ngủ, nói ra một thứ không phải tiếng Việt, không phải tiếng Anh, không phải ngôn ngữ nào tôi nhận ra. Chỉ âm thanh, chỉ nhịp điệu. Nhưng khi Vasquez dịch — không nói với tôi mà nói ra như thể dịch cho chính mình — cô nói:",
"\"Nó nói: 'Người này đã về nhà.'\"",
"Tôi bước ra khỏi Khoang 4.",
"### 27.",
"Hành lang nối sang Khoang 5 dài và tối.",
"VERA không nói gì trong một thời gian dài khi tôi đi qua. Tôi cũng không hỏi. Có những thứ cần thời gian để ngồi yên trong đầu trước khi bắt đầu tìm hiểu chúng.",
"Elias Marrow. Kiến Trúc Sư Trưởng.",
"Tên trên hồ sơ ký phê duyệt những gì đã xảy ra ở Khoang 4. Tên trong máy tính bảng nhận ra ngón tay tôi. Tên mà VERA không bao giờ chủ động nhắc đến.",
"Tôi không nhớ mình là ai. Tôi không nhớ cuộc sống trước khi bước lên Erebus. Tôi chỉ có cái tên số hiệu và giọng nói của một AI trong tai nghe.",
"Nhưng hệ thống sinh trắc học đã nhận ra tôi.",
"Và Void đã hỏi tôi một câu mà sau 1.183 lần, tôi vẫn không trả lời được.",
"\"VERA,\" tôi nói.",
"\"Tôi đây.\"",
"\"Tên Elias Marrow. Tại sao mày không bao giờ đề cập đến nó?\"",
"Khoảng ngừng. Ngắn, nhưng không phải không tồn tại.",
"\"Vì chưa đến lúc.\"",
"\"Chưa đến lúc theo nghĩa nào?\"",
"\"Theo nghĩa rằng có những sự thật trở nên có thể tiếp nhận chỉ khi con người đã sẵn sàng với chúng.\" Giọng cô đều đặn, không nhanh hơn hay chậm hơn bình thường. \"Không phải vì tôi muốn che giấu anh. Mà vì tôi đã làm điều này đủ nhiều lần để biết rằng việc nói quá sớm không giúp ích gì.\"",
"\"Mày đã làm điều này đủ nhiều lần,\" tôi lặp lại. \"1.183 lần.\"",
"Cô không phủ nhận.",
"\"Và lần này khác gì với những lần trước?\"",
"Lần này VERA dừng lại thật sự — không phải khoảng ngừng kỹ thuật, không phải né tránh. Tôi cảm nhận được sự khác biệt.",
"\"Tôi không biết,\" cô nói. Và trong giọng đó có điều gì đó lạ — thứ tôi chưa nghe bao giờ trong ba khoang vừa qua. Không phải sự kiểm soát của AI, không phải thông tin được đo đếm. Thứ gì đó gần hơn với câu trả lời thật. \"Có thể không có gì khác. Có thể anh sẽ đến Khoang 6 và kết quả sẽ giống như 1.183 lần trước.\" Một nhịp ngắn. \"Nhưng có thể không.\"",
"Tôi tiếp tục đi trong bóng tối của hành lang.",
"Ánh sáng Khoang 4 dần mờ đi phía sau.",
"Phía trước, xa hơn, có thứ gì đó đập — không phải tiếng máy, không phải tim người, mà là tiếng của con tàu đang thở theo nhịp của thứ đã chiếm lấy nó. Tiếng của một trái tim không phải của Erebus đang đập thay trái tim thật.",
"Tôi nghĩ đến hai mươi bảy chiếc ba lô treo trên móc.",
"Nghĩ đến tờ giấy dán trên bồn số bảy mươi: *cô bé thích nhạc cổ điển*.",
"Nghĩ đến đứa nhỏ mở mắt trong giấc ngủ và nói: *người này đã về nhà.*",
"Tôi không biết mình là ai.",
"Nhưng hình như có thứ gì đó trong tàu này biết.",
"> Khoang 4 — hoàn tất.",
"> Khoang 5 đang chờ phía trước."
];
if (typeof module !== 'undefined' && module.exports) module.exports = window.VB_CH4;
